// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package receiptdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReceiptAnchor struct {
	Root        string             `db:"root" json:"root"`
	Cluster     string             `db:"cluster" json:"cluster"`
	Transaction string             `db:"transaction" json:"transaction"`
	AnchorKey   string             `db:"anchor_key" json:"anchor_key"`
	AnchoredAt  pgtype.Timestamptz `db:"anchored_at" json:"anchored_at"`
}

type ReceiptAnchorKey struct {
	Key        string             `db:"key" json:"key"`
	ActiveFrom pgtype.Timestamptz `db:"active_from" json:"active_from"`
	ActiveTo   pgtype.Timestamptz `db:"active_to" json:"active_to"`
}

type ReceiptBatch struct {
	Root      string             `db:"root" json:"root"`
	LeafCount int32              `db:"leaf_count" json:"leaf_count"`
	SealedAt  pgtype.Timestamptz `db:"sealed_at" json:"sealed_at"`
}

type ReceiptBatchLeafe struct {
	Root     string `db:"root" json:"root"`
	Position int32  `db:"position" json:"position"`
	Serial   string `db:"serial" json:"serial"`
}

type ReceiptReceipt struct {
	Serial            string             `db:"serial" json:"serial"`
	PublicBody        []byte             `db:"public_body" json:"public_body"`
	PrivateCommitment string             `db:"private_commitment" json:"private_commitment"`
	Leaf              string             `db:"leaf" json:"leaf"`
	IssuedAt          pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
}

type ReceiptSerial struct {
	Period      string             `db:"period" json:"period"`
	Sequence    int64              `db:"sequence" json:"sequence"`
	Serial      string             `db:"serial" json:"serial"`
	AllocatedAt pgtype.Timestamptz `db:"allocated_at" json:"allocated_at"`
}

type ReceiptSerialCounter struct {
	Period string `db:"period" json:"period"`
	Last   int64  `db:"last" json:"last"`
}
