// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package receiptdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeAnchorKey = `-- name: ActiveAnchorKey :one
SELECT key, active_from, active_to FROM receipt.anchor_keys WHERE active_to IS NULL
`

func (q *Queries) ActiveAnchorKey(ctx context.Context) (ReceiptAnchorKey, error) {
	row := q.db.QueryRow(ctx, activeAnchorKey)
	var i ReceiptAnchorKey
	err := row.Scan(&i.Key, &i.ActiveFrom, &i.ActiveTo)
	return i, err
}

const allocateSerial = `-- name: AllocateSerial :exec
INSERT INTO receipt.serials (period, sequence, serial, allocated_at)
VALUES ($1, $2, $3, $4)
`

type AllocateSerialParams struct {
	Period      string             `db:"period" json:"period"`
	Sequence    int64              `db:"sequence" json:"sequence"`
	Serial      string             `db:"serial" json:"serial"`
	AllocatedAt pgtype.Timestamptz `db:"allocated_at" json:"allocated_at"`
}

// No ON CONFLICT: a reused sequence is refused outright. The serial is
// formatted in Go (receipt.FormatSerial), once.
func (q *Queries) AllocateSerial(ctx context.Context, arg AllocateSerialParams) error {
	_, err := q.db.Exec(ctx, allocateSerial,
		arg.Period,
		arg.Sequence,
		arg.Serial,
		arg.AllocatedAt,
	)
	return err
}

const batchForSerial = `-- name: BatchForSerial :one
SELECT b.root, b.leaf_count, b.sealed_at FROM receipt.batches b
JOIN receipt.batch_leaves l ON l.root = b.root
WHERE l.serial = $1
`

func (q *Queries) BatchForSerial(ctx context.Context, serial string) (ReceiptBatch, error) {
	row := q.db.QueryRow(ctx, batchForSerial, serial)
	var i ReceiptBatch
	err := row.Scan(&i.Root, &i.LeafCount, &i.SealedAt)
	return i, err
}

const batchLeaves = `-- name: BatchLeaves :many
SELECT l.position, l.serial, r.leaf, r.public_body, r.private_commitment
FROM receipt.batch_leaves l
JOIN receipt.receipts r ON r.serial = l.serial
WHERE l.root = $1
ORDER BY l.position
`

type BatchLeavesRow struct {
	Position          int32  `db:"position" json:"position"`
	Serial            string `db:"serial" json:"serial"`
	Leaf              string `db:"leaf" json:"leaf"`
	PublicBody        []byte `db:"public_body" json:"public_body"`
	PrivateCommitment string `db:"private_commitment" json:"private_commitment"`
}

// In position order: the order the root was computed in, which is the only
// order a proof built from them verifies against.
func (q *Queries) BatchLeaves(ctx context.Context, root string) ([]BatchLeavesRow, error) {
	rows, err := q.db.Query(ctx, batchLeaves, root)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchLeavesRow
	for rows.Next() {
		var i BatchLeavesRow
		if err := rows.Scan(
			&i.Position,
			&i.Serial,
			&i.Leaf,
			&i.PublicBody,
			&i.PrivateCommitment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnchor = `-- name: GetAnchor :one
SELECT root, cluster, transaction, anchor_key, anchored_at FROM receipt.anchors WHERE root = $1
`

func (q *Queries) GetAnchor(ctx context.Context, root string) (ReceiptAnchor, error) {
	row := q.db.QueryRow(ctx, getAnchor, root)
	var i ReceiptAnchor
	err := row.Scan(
		&i.Root,
		&i.Cluster,
		&i.Transaction,
		&i.AnchorKey,
		&i.AnchoredAt,
	)
	return i, err
}

const getBatch = `-- name: GetBatch :one
SELECT root, leaf_count, sealed_at FROM receipt.batches WHERE root = $1
`

func (q *Queries) GetBatch(ctx context.Context, root string) (ReceiptBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, root)
	var i ReceiptBatch
	err := row.Scan(&i.Root, &i.LeafCount, &i.SealedAt)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT serial, public_body, private_commitment, leaf, issued_at FROM receipt.receipts WHERE serial = $1
`

func (q *Queries) GetReceipt(ctx context.Context, serial string) (ReceiptReceipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, serial)
	var i ReceiptReceipt
	err := row.Scan(
		&i.Serial,
		&i.PublicBody,
		&i.PrivateCommitment,
		&i.Leaf,
		&i.IssuedAt,
	)
	return i, err
}

const insertAnchor = `-- name: InsertAnchor :exec
INSERT INTO receipt.anchors (root, cluster, transaction, anchor_key, anchored_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAnchorParams struct {
	Root        string             `db:"root" json:"root"`
	Cluster     string             `db:"cluster" json:"cluster"`
	Transaction string             `db:"transaction" json:"transaction"`
	AnchorKey   string             `db:"anchor_key" json:"anchor_key"`
	AnchoredAt  pgtype.Timestamptz `db:"anchored_at" json:"anchored_at"`
}

func (q *Queries) InsertAnchor(ctx context.Context, arg InsertAnchorParams) error {
	_, err := q.db.Exec(ctx, insertAnchor,
		arg.Root,
		arg.Cluster,
		arg.Transaction,
		arg.AnchorKey,
		arg.AnchoredAt,
	)
	return err
}

const insertAnchorKey = `-- name: InsertAnchorKey :exec
INSERT INTO receipt.anchor_keys (key, active_from)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type InsertAnchorKeyParams struct {
	Key        string             `db:"key" json:"key"`
	ActiveFrom pgtype.Timestamptz `db:"active_from" json:"active_from"`
}

func (q *Queries) InsertAnchorKey(ctx context.Context, arg InsertAnchorKeyParams) error {
	_, err := q.db.Exec(ctx, insertAnchorKey, arg.Key, arg.ActiveFrom)
	return err
}

const insertBatch = `-- name: InsertBatch :exec
INSERT INTO receipt.batches (root, leaf_count, sealed_at)
VALUES ($1, $2, $3)
ON CONFLICT (root) DO NOTHING
`

type InsertBatchParams struct {
	Root      string             `db:"root" json:"root"`
	LeafCount int32              `db:"leaf_count" json:"leaf_count"`
	SealedAt  pgtype.Timestamptz `db:"sealed_at" json:"sealed_at"`
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) error {
	_, err := q.db.Exec(ctx, insertBatch, arg.Root, arg.LeafCount, arg.SealedAt)
	return err
}

const insertBatchLeaf = `-- name: InsertBatchLeaf :exec
INSERT INTO receipt.batch_leaves (root, position, serial)
VALUES ($1, $2, $3)
ON CONFLICT (root, position) DO NOTHING
`

type InsertBatchLeafParams struct {
	Root     string `db:"root" json:"root"`
	Position int32  `db:"position" json:"position"`
	Serial   string `db:"serial" json:"serial"`
}

func (q *Queries) InsertBatchLeaf(ctx context.Context, arg InsertBatchLeafParams) error {
	_, err := q.db.Exec(ctx, insertBatchLeaf, arg.Root, arg.Position, arg.Serial)
	return err
}

const insertReceipt = `-- name: InsertReceipt :exec
INSERT INTO receipt.receipts (serial, public_body, private_commitment, leaf, issued_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (serial) DO NOTHING
`

type InsertReceiptParams struct {
	Serial            string             `db:"serial" json:"serial"`
	PublicBody        []byte             `db:"public_body" json:"public_body"`
	PrivateCommitment string             `db:"private_commitment" json:"private_commitment"`
	Leaf              string             `db:"leaf" json:"leaf"`
	IssuedAt          pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) error {
	_, err := q.db.Exec(ctx, insertReceipt,
		arg.Serial,
		arg.PublicBody,
		arg.PrivateCommitment,
		arg.Leaf,
		arg.IssuedAt,
	)
	return err
}

const listAnchorKeys = `-- name: ListAnchorKeys :many
SELECT key, active_from, active_to FROM receipt.anchor_keys ORDER BY active_from
`

func (q *Queries) ListAnchorKeys(ctx context.Context) ([]ReceiptAnchorKey, error) {
	rows, err := q.db.Query(ctx, listAnchorKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptAnchorKey
	for rows.Next() {
		var i ReceiptAnchorKey
		if err := rows.Scan(&i.Key, &i.ActiveFrom, &i.ActiveTo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSequence = `-- name: NextSequence :one
INSERT INTO receipt.serial_counters (period, last) VALUES ($1, 1)
ON CONFLICT (period) DO UPDATE SET last = receipt.serial_counters.last + 1
RETURNING last
`

// One statement: the row lock on the month's counter serializes concurrent
// callers, so each gets the next sequence with no retry.
func (q *Queries) NextSequence(ctx context.Context, period string) (int64, error) {
	row := q.db.QueryRow(ctx, nextSequence, period)
	var last int64
	err := row.Scan(&last)
	return last, err
}

const raiseCounter = `-- name: RaiseCounter :exec
INSERT INTO receipt.serial_counters (period, last) VALUES ($1, $2)
ON CONFLICT (period) DO UPDATE SET last = GREATEST(receipt.serial_counters.last, EXCLUDED.last)
`

type RaiseCounterParams struct {
	Period string `db:"period" json:"period"`
	Last   int64  `db:"last" json:"last"`
}

// Keeps the counter at or above a replayed sequence, so the next allocation
// after a replay continues past it instead of colliding with it.
func (q *Queries) RaiseCounter(ctx context.Context, arg RaiseCounterParams) error {
	_, err := q.db.Exec(ctx, raiseCounter, arg.Period, arg.Last)
	return err
}

const receiptsBySerial = `-- name: ReceiptsBySerial :many
SELECT serial, public_body, private_commitment, leaf, issued_at FROM receipt.receipts WHERE serial = ANY($1::text[])
`

func (q *Queries) ReceiptsBySerial(ctx context.Context, serials []string) ([]ReceiptReceipt, error) {
	rows, err := q.db.Query(ctx, receiptsBySerial, serials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptReceipt
	for rows.Next() {
		var i ReceiptReceipt
		if err := rows.Scan(
			&i.Serial,
			&i.PublicBody,
			&i.PrivateCommitment,
			&i.Leaf,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSerial = `-- name: RecordSerial :exec
INSERT INTO receipt.serials (period, sequence, serial, allocated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (period, sequence) DO NOTHING
`

type RecordSerialParams struct {
	Period      string             `db:"period" json:"period"`
	Sequence    int64              `db:"sequence" json:"sequence"`
	Serial      string             `db:"serial" json:"serial"`
	AllocatedAt pgtype.Timestamptz `db:"allocated_at" json:"allocated_at"`
}

// For replaying receipts whose serials were allocated before this ledger
// existed: the row an allocation would have written, at its own sequence. A
// conflict means it is already recorded.
func (q *Queries) RecordSerial(ctx context.Context, arg RecordSerialParams) error {
	_, err := q.db.Exec(ctx, recordSerial,
		arg.Period,
		arg.Sequence,
		arg.Serial,
		arg.AllocatedAt,
	)
	return err
}

const unanchoredBatches = `-- name: UnanchoredBatches :many
SELECT b.root, b.leaf_count, b.sealed_at FROM receipt.batches b
LEFT JOIN receipt.anchors a ON a.root = b.root
WHERE a.root IS NULL
ORDER BY b.sealed_at, b.root
`

func (q *Queries) UnanchoredBatches(ctx context.Context) ([]ReceiptBatch, error) {
	rows, err := q.db.Query(ctx, unanchoredBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptBatch
	for rows.Next() {
		var i ReceiptBatch
		if err := rows.Scan(&i.Root, &i.LeafCount, &i.SealedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsealedReceipts = `-- name: UnsealedReceipts :many
SELECT r.serial, r.public_body, r.private_commitment, r.leaf, r.issued_at FROM receipt.receipts r
LEFT JOIN receipt.batch_leaves l ON l.serial = r.serial
WHERE l.serial IS NULL
ORDER BY r.issued_at, r.serial
`

// Issued and not yet in any batch, oldest first, so a batch seals receipts
// in the order they were issued.
func (q *Queries) UnsealedReceipts(ctx context.Context) ([]ReceiptReceipt, error) {
	rows, err := q.db.Query(ctx, unsealedReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptReceipt
	for rows.Next() {
		var i ReceiptReceipt
		if err := rows.Scan(
			&i.Serial,
			&i.PublicBody,
			&i.PrivateCommitment,
			&i.Leaf,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
