//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAlloys Every alloy, read from chain.
	// (GET /alloys)
	ListAlloys(w http.ResponseWriter, r *http.Request, params ListAlloysParams)
	// GetAlloy An alloy's recipe, supply, each leg's ledger, pending and unclaimed balances, and held-back legs (chain/programs/hall/src/state.rs::Alloy, with held_back derived by checking each leg's own account for a freeze, since the program stores no such flag).
	// (GET /alloys/{address})
	GetAlloy(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyParams)
	// GetAlloyMeltProceeds What a melt of n shares returns per leg, rounded down, and what the Hall keeps.
	// (GET /alloys/{address}/melt-proceeds)
	GetAlloyMeltProceeds(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyMeltProceedsParams)
	// GetAlloyNav Off-chain NAV against share price. Until an oracle read and a share pool exist (docs/prd/API.md section 14) this always answers completeness: partial, with missing parts nav (NAV_NO_PRICE_SOURCE) and share_price (SHARE_PRICE_NO_POOL), never a placeholder figure.
	// (GET /alloys/{address}/nav)
	GetAlloyNav(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyNavParams)
	// GetAlloyStrikeCost What a strike of n shares takes per leg, rounded up.
	// (GET /alloys/{address}/strike-cost)
	GetAlloyStrikeCost(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyStrikeCostParams)
	// ListAnchorKeys The published list of keys allowed to anchor a root, with rotation dates.
	// (GET /anchor-keys)
	ListAnchorKeys(w http.ResponseWriter, r *http.Request)
	// GetBatch A sealed batch, its leaves' public digests and its anchor.
	// (GET /batches/{root})
	GetBatch(w http.ResponseWriter, r *http.Request, root string)
	// ListFindings Every published finding a visitor can reproduce by running one command.
	// (GET /findings)
	ListFindings(w http.ResponseWriter, r *http.Request)
	// GetFinding One finding, with what it does not establish stated beside it.
	// (GET /findings/{slug})
	GetFinding(w http.ResponseWriter, r *http.Request, slug string)
	// EvaluateFormula Admissibility, required atoms and stored depth for a formula not yet on chain, per leg, at most MAX_CONSTITUENTS (12, chain/programs/hall/src/state.rs).
	// (POST /formulas/evaluate)
	EvaluateFormula(w http.ResponseWriter, r *http.Request)
	// GetHallDemonstration The demonstration transcript for one cluster: every scenario, its steps, actors, results, reasons, and, on devnet, transaction signatures. docs/prd/HALL.md section 7.
	// (GET /hall/demonstration)
	GetHallDemonstration(w http.ResponseWriter, r *http.Request, params GetHallDemonstrationParams)
	// ListInstruments Every instrument in the registry.
	// (GET /instruments)
	ListInstruments(w http.ResponseWriter, r *http.Request, params ListInstrumentsParams)
	// GetInstrument Identity, grade, decoded prerogatives with their sentences, the live multiplier and the field it came from, unknown extensions, and the capture slot.
	// (GET /instruments/{mint})
	GetInstrument(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentParams)
	// GetInstrumentAdmissibility The policy decision for this instrument, with reasons, version and digest.
	// (GET /instruments/{mint}/admissibility)
	GetInstrumentAdmissibility(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentAdmissibilityParams)
	// GetInstrumentDepth Depth at size as a curve, with each quote's age and expiry. Selling reports unavailable until it is measured (docs/prd/API.md 5.1).
	// (GET /instruments/{mint}/depth)
	GetInstrumentDepth(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentDepthParams)
	// GetPolicy A policy document, as data (server/internal/policy.Document).
	// (GET /policies/{version})
	GetPolicy(w http.ResponseWriter, r *http.Request, version PolicyVersion)
	// ListReasonCodes Every reason code and its fixed meaning.
	// (GET /reason-codes)
	ListReasonCodes(w http.ResponseWriter, r *http.Request)
	// GetReceipt The public body, its inclusion proof, its batch root and the anchor transaction. Shaped so the verification ritual needs nothing else (docs/prd/EXPLORER.md section 3.1).
	// (GET /receipts/{serial})
	GetReceipt(w http.ResponseWriter, r *http.Request, serial string)
	// GetStatus Seametry's own freshness: ledger lag, observer age per instrument and source, seal backlog, in the same evidence shape as any source.
	// (GET /status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// StreamEvents Public live change over server-sent events (docs/prd/API.md section 6).
	// (GET /stream)
	StreamEvents(w http.ResponseWriter, r *http.Request, params StreamEventsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAlloys operation middleware
func (siw *ServerInterfaceWrapper) ListAlloys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAlloysParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cluster" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cluster", r.URL.Query(), &params.Cluster, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cluster"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAlloys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlloy operation middleware
func (siw *ServerInterfaceWrapper) GetAlloy(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address AlloyAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlloyParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlloy(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlloyMeltProceeds operation middleware
func (siw *ServerInterfaceWrapper) GetAlloyMeltProceeds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address AlloyAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlloyMeltProceedsParams

	// ------------- Required query parameter "shares" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "shares", r.URL.Query(), &params.Shares, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "shares"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shares", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlloyMeltProceeds(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlloyNav operation middleware
func (siw *ServerInterfaceWrapper) GetAlloyNav(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address AlloyAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlloyNavParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlloyNav(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlloyStrikeCost operation middleware
func (siw *ServerInterfaceWrapper) GetAlloyStrikeCost(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "address" -------------
	var address AlloyAddress

	err = runtime.BindStyledParameterWithOptions("simple", "address", r.PathValue("address"), &address, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlloyStrikeCostParams

	// ------------- Required query parameter "shares" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "shares", r.URL.Query(), &params.Shares, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "shares"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shares", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlloyStrikeCost(w, r, address, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAnchorKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAnchorKeys(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAnchorKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBatch operation middleware
func (siw *ServerInterfaceWrapper) GetBatch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "root" -------------
	var root string

	err = runtime.BindStyledParameterWithOptions("simple", "root", r.PathValue("root"), &root, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "root", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBatch(w, r, root)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFindings operation middleware
func (siw *ServerInterfaceWrapper) ListFindings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFindings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFinding operation middleware
func (siw *ServerInterfaceWrapper) GetFinding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFinding(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvaluateFormula operation middleware
func (siw *ServerInterfaceWrapper) EvaluateFormula(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvaluateFormula(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHallDemonstration operation middleware
func (siw *ServerInterfaceWrapper) GetHallDemonstration(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHallDemonstrationParams

	// ------------- Required query parameter "cluster" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "cluster", r.URL.Query(), &params.Cluster, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cluster"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cluster", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHallDemonstration(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInstruments operation middleware
func (siw *ServerInterfaceWrapper) ListInstruments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstrumentsParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstruments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstrument operation middleware
func (siw *ServerInterfaceWrapper) GetInstrument(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "mint" -------------
	var mint Mint

	err = runtime.BindStyledParameterWithOptions("simple", "mint", r.PathValue("mint"), &mint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mint", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInstrumentParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstrument(w, r, mint, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstrumentAdmissibility operation middleware
func (siw *ServerInterfaceWrapper) GetInstrumentAdmissibility(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "mint" -------------
	var mint Mint

	err = runtime.BindStyledParameterWithOptions("simple", "mint", r.PathValue("mint"), &mint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mint", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInstrumentAdmissibilityParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstrumentAdmissibility(w, r, mint, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstrumentDepth operation middleware
func (siw *ServerInterfaceWrapper) GetInstrumentDepth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "mint" -------------
	var mint Mint

	err = runtime.BindStyledParameterWithOptions("simple", "mint", r.PathValue("mint"), &mint, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mint", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInstrumentDepthParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", r.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "direction"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstrumentDepth(w, r, mint, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPolicy operation middleware
func (siw *ServerInterfaceWrapper) GetPolicy(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "version" -------------
	var version PolicyVersion

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicy(w, r, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReasonCodes operation middleware
func (siw *ServerInterfaceWrapper) ListReasonCodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReasonCodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReceipt operation middleware
func (siw *ServerInterfaceWrapper) GetReceipt(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serial" -------------
	var serial string

	err = runtime.BindStyledParameterWithOptions("simple", "serial", r.PathValue("serial"), &serial, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serial", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReceipt(w, r, serial)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamEvents operation middleware
func (siw *ServerInterfaceWrapper) StreamEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamEventsParams

	headers := r.Header

	// ------------- Optional header parameter "Last-Event-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Last-Event-ID")]; found {
		var LastEventID string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Last-Event-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Last-Event-ID", valueList[0], &LastEventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Last-Event-ID", Err: err})
			return
		}

		params.LastEventID = &LastEventID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/instruments", wrapper.ListInstruments)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/instruments/{mint}", wrapper.GetInstrument)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/instruments/{mint}/admissibility", wrapper.GetInstrumentAdmissibility)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/instruments/{mint}/depth", wrapper.GetInstrumentDepth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/findings", wrapper.ListFindings)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/findings/{slug}", wrapper.GetFinding)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/hall/demonstration", wrapper.GetHallDemonstration)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/alloys", wrapper.ListAlloys)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/alloys/{address}", wrapper.GetAlloy)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/alloys/{address}/nav", wrapper.GetAlloyNav)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/alloys/{address}/strike-cost", wrapper.GetAlloyStrikeCost)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/alloys/{address}/melt-proceeds", wrapper.GetAlloyMeltProceeds)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/formulas/evaluate", wrapper.EvaluateFormula)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/policies/{version}", wrapper.GetPolicy)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reason-codes", wrapper.ListReasonCodes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/stream", wrapper.StreamEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/receipts/{serial}", wrapper.GetReceipt)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/batches/{root}", wrapper.GetBatch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/anchor-keys", wrapper.ListAnchorKeys)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/status", wrapper.GetStatus)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListAlloysRequestObject struct {
	Params ListAlloysParams
}

type ListAlloysResponseObject interface {
	VisitListAlloysResponse(w http.ResponseWriter) error
}

type ListAlloys200JSONResponse struct {
	Data []Alloy `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response ListAlloys200JSONResponse) VisitListAlloysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAlloysdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAlloysdefaultApplicationProblemPlusJSONResponse) VisitListAlloysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyRequestObject struct {
	Address AlloyAddress `json:"address"`
	Params  GetAlloyParams
}

type GetAlloyResponseObject interface {
	VisitGetAlloyResponse(w http.ResponseWriter) error
}

type GetAlloy200JSONResponse struct {
	// Data An alloy read from chain (chain/programs/hall/src/state.rs::Alloy).
	Data Alloy `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetAlloy200JSONResponse) VisitGetAlloyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAlloydefaultApplicationProblemPlusJSONResponse) VisitGetAlloyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyMeltProceedsRequestObject struct {
	Address AlloyAddress `json:"address"`
	Params  GetAlloyMeltProceedsParams
}

type GetAlloyMeltProceedsResponseObject interface {
	VisitGetAlloyMeltProceedsResponse(w http.ResponseWriter) error
}

type GetAlloyMeltProceeds200JSONResponse struct {
	// Data What a strike takes or a melt returns, per leg, at one share count.
	Data CostRow `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetAlloyMeltProceeds200JSONResponse) VisitGetAlloyMeltProceedsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyMeltProceedsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAlloyMeltProceedsdefaultApplicationProblemPlusJSONResponse) VisitGetAlloyMeltProceedsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyNavRequestObject struct {
	Address AlloyAddress `json:"address"`
	Params  GetAlloyNavParams
}

type GetAlloyNavResponseObject interface {
	VisitGetAlloyNavResponse(w http.ResponseWriter) error
}

type GetAlloyNav200JSONResponse struct {
	// Data Every field is absent until its source exists; meta.missing names why (docs/prd/API.md section 14). Never a placeholder figure.
	Data Nav `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetAlloyNav200JSONResponse) VisitGetAlloyNavResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyNavdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAlloyNavdefaultApplicationProblemPlusJSONResponse) VisitGetAlloyNavResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyStrikeCostRequestObject struct {
	Address AlloyAddress `json:"address"`
	Params  GetAlloyStrikeCostParams
}

type GetAlloyStrikeCostResponseObject interface {
	VisitGetAlloyStrikeCostResponse(w http.ResponseWriter) error
}

type GetAlloyStrikeCost200JSONResponse struct {
	// Data What a strike takes or a melt returns, per leg, at one share count.
	Data CostRow `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetAlloyStrikeCost200JSONResponse) VisitGetAlloyStrikeCostResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAlloyStrikeCostdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAlloyStrikeCostdefaultApplicationProblemPlusJSONResponse) VisitGetAlloyStrikeCostResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListAnchorKeysRequestObject struct {
}

type ListAnchorKeysResponseObject interface {
	VisitListAnchorKeysResponse(w http.ResponseWriter) error
}

type ListAnchorKeys200JSONResponse struct {
	Data []AnchorKey `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response ListAnchorKeys200JSONResponse) VisitListAnchorKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAnchorKeysdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListAnchorKeysdefaultApplicationProblemPlusJSONResponse) VisitListAnchorKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetBatchRequestObject struct {
	Root string `json:"root"`
}

type GetBatchResponseObject interface {
	VisitGetBatchResponse(w http.ResponseWriter) error
}

type GetBatch200JSONResponse struct {
	Data Batch `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetBatch200JSONResponse) VisitGetBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBatchdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetBatchdefaultApplicationProblemPlusJSONResponse) VisitGetBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindingsRequestObject struct {
}

type ListFindingsResponseObject interface {
	VisitListFindingsResponse(w http.ResponseWriter) error
}

type ListFindings200JSONResponse struct {
	Data []Finding `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response ListFindings200JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindingsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListFindingsdefaultApplicationProblemPlusJSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetFindingRequestObject struct {
	Slug string `json:"slug"`
}

type GetFindingResponseObject interface {
	VisitGetFindingResponse(w http.ResponseWriter) error
}

type GetFinding200JSONResponse struct {
	Data Finding `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetFinding200JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFindingdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetFindingdefaultApplicationProblemPlusJSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateFormulaRequestObject struct {
	Body *EvaluateFormulaJSONRequestBody
}

type EvaluateFormulaResponseObject interface {
	VisitEvaluateFormulaResponse(w http.ResponseWriter) error
}

type EvaluateFormula200JSONResponse struct {
	Data FormulaEvaluateResult `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response EvaluateFormula200JSONResponse) VisitEvaluateFormulaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateFormuladefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response EvaluateFormuladefaultApplicationProblemPlusJSONResponse) VisitEvaluateFormulaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetHallDemonstrationRequestObject struct {
	Params GetHallDemonstrationParams
}

type GetHallDemonstrationResponseObject interface {
	VisitGetHallDemonstrationResponse(w http.ResponseWriter) error
}

type GetHallDemonstration200JSONResponse struct {
	// Data The shape server/cmd/explorer/hall.go decodes today, published at this contract's field names (docs/prd/HALL.md section 7).
	Data HallTranscript `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetHallDemonstration200JSONResponse) VisitGetHallDemonstrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHallDemonstrationdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetHallDemonstrationdefaultApplicationProblemPlusJSONResponse) VisitGetHallDemonstrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentsRequestObject struct {
	Params ListInstrumentsParams
}

type ListInstrumentsResponseObject interface {
	VisitListInstrumentsResponse(w http.ResponseWriter) error
}

type ListInstruments200JSONResponse struct {
	Data []Instrument `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response ListInstruments200JSONResponse) VisitListInstrumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstrumentsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListInstrumentsdefaultApplicationProblemPlusJSONResponse) VisitListInstrumentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentRequestObject struct {
	Mint   Mint `json:"mint"`
	Params GetInstrumentParams
}

type GetInstrumentResponseObject interface {
	VisitGetInstrumentResponse(w http.ResponseWriter) error
}

type GetInstrument200JSONResponse struct {
	Data Instrument `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetInstrument200JSONResponse) VisitGetInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetInstrumentdefaultApplicationProblemPlusJSONResponse) VisitGetInstrumentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentAdmissibilityRequestObject struct {
	Mint   Mint `json:"mint"`
	Params GetInstrumentAdmissibilityParams
}

type GetInstrumentAdmissibilityResponseObject interface {
	VisitGetInstrumentAdmissibilityResponse(w http.ResponseWriter) error
}

type GetInstrumentAdmissibility200JSONResponse struct {
	Data Decision `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetInstrumentAdmissibility200JSONResponse) VisitGetInstrumentAdmissibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentAdmissibilitydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetInstrumentAdmissibilitydefaultApplicationProblemPlusJSONResponse) VisitGetInstrumentAdmissibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentDepthRequestObject struct {
	Mint   Mint `json:"mint"`
	Params GetInstrumentDepthParams
}

type GetInstrumentDepthResponseObject interface {
	VisitGetInstrumentDepthResponse(w http.ResponseWriter) error
}

type GetInstrumentDepth200JSONResponse struct {
	Data DepthCurve `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetInstrumentDepth200JSONResponse) VisitGetInstrumentDepthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstrumentDepthdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetInstrumentDepthdefaultApplicationProblemPlusJSONResponse) VisitGetInstrumentDepthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicyRequestObject struct {
	Version PolicyVersion `json:"version"`
}

type GetPolicyResponseObject interface {
	VisitGetPolicyResponse(w http.ResponseWriter) error
}

type GetPolicy200JSONResponse struct {
	// Data server/internal/policy.Document, as published.
	Data PolicyDocument `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetPolicy200JSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetPolicydefaultApplicationProblemPlusJSONResponse) VisitGetPolicyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListReasonCodesRequestObject struct {
}

type ListReasonCodesResponseObject interface {
	VisitListReasonCodesResponse(w http.ResponseWriter) error
}

type ListReasonCodes200JSONResponse struct {
	Data []ReasonCodeEntry `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response ListReasonCodes200JSONResponse) VisitListReasonCodesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReasonCodesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListReasonCodesdefaultApplicationProblemPlusJSONResponse) VisitListReasonCodesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetReceiptRequestObject struct {
	Serial string `json:"serial"`
}

type GetReceiptResponseObject interface {
	VisitGetReceiptResponse(w http.ResponseWriter) error
}

type GetReceipt200JSONResponse struct {
	Data Proof `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetReceipt200JSONResponse) VisitGetReceiptResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReceiptdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetReceiptdefaultApplicationProblemPlusJSONResponse) VisitGetReceiptResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200JSONResponse struct {
	Data StatusReport `json:"data"`

	// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
	Meta Meta `json:"meta"`
}

func (response GetStatus200JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetStatusdefaultApplicationProblemPlusJSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type StreamEventsRequestObject struct {
	Params StreamEventsParams
}

type StreamEventsResponseObject interface {
	VisitStreamEventsResponse(w http.ResponseWriter) error
}

type StreamEvents200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamEvents200TexteventStreamResponse) VisitStreamEventsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type StreamEventsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response StreamEventsdefaultApplicationProblemPlusJSONResponse) VisitStreamEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAlloys Every alloy, read from chain.
	// (GET /alloys)
	ListAlloys(ctx context.Context, request ListAlloysRequestObject) (ListAlloysResponseObject, error)
	// GetAlloy An alloy's recipe, supply, each leg's ledger, pending and unclaimed balances, and held-back legs (chain/programs/hall/src/state.rs::Alloy, with held_back derived by checking each leg's own account for a freeze, since the program stores no such flag).
	// (GET /alloys/{address})
	GetAlloy(ctx context.Context, request GetAlloyRequestObject) (GetAlloyResponseObject, error)
	// GetAlloyMeltProceeds What a melt of n shares returns per leg, rounded down, and what the Hall keeps.
	// (GET /alloys/{address}/melt-proceeds)
	GetAlloyMeltProceeds(ctx context.Context, request GetAlloyMeltProceedsRequestObject) (GetAlloyMeltProceedsResponseObject, error)
	// GetAlloyNav Off-chain NAV against share price. Until an oracle read and a share pool exist (docs/prd/API.md section 14) this always answers completeness: partial, with missing parts nav (NAV_NO_PRICE_SOURCE) and share_price (SHARE_PRICE_NO_POOL), never a placeholder figure.
	// (GET /alloys/{address}/nav)
	GetAlloyNav(ctx context.Context, request GetAlloyNavRequestObject) (GetAlloyNavResponseObject, error)
	// GetAlloyStrikeCost What a strike of n shares takes per leg, rounded up.
	// (GET /alloys/{address}/strike-cost)
	GetAlloyStrikeCost(ctx context.Context, request GetAlloyStrikeCostRequestObject) (GetAlloyStrikeCostResponseObject, error)
	// ListAnchorKeys The published list of keys allowed to anchor a root, with rotation dates.
	// (GET /anchor-keys)
	ListAnchorKeys(ctx context.Context, request ListAnchorKeysRequestObject) (ListAnchorKeysResponseObject, error)
	// GetBatch A sealed batch, its leaves' public digests and its anchor.
	// (GET /batches/{root})
	GetBatch(ctx context.Context, request GetBatchRequestObject) (GetBatchResponseObject, error)
	// ListFindings Every published finding a visitor can reproduce by running one command.
	// (GET /findings)
	ListFindings(ctx context.Context, request ListFindingsRequestObject) (ListFindingsResponseObject, error)
	// GetFinding One finding, with what it does not establish stated beside it.
	// (GET /findings/{slug})
	GetFinding(ctx context.Context, request GetFindingRequestObject) (GetFindingResponseObject, error)
	// EvaluateFormula Admissibility, required atoms and stored depth for a formula not yet on chain, per leg, at most MAX_CONSTITUENTS (12, chain/programs/hall/src/state.rs).
	// (POST /formulas/evaluate)
	EvaluateFormula(ctx context.Context, request EvaluateFormulaRequestObject) (EvaluateFormulaResponseObject, error)
	// GetHallDemonstration The demonstration transcript for one cluster: every scenario, its steps, actors, results, reasons, and, on devnet, transaction signatures. docs/prd/HALL.md section 7.
	// (GET /hall/demonstration)
	GetHallDemonstration(ctx context.Context, request GetHallDemonstrationRequestObject) (GetHallDemonstrationResponseObject, error)
	// ListInstruments Every instrument in the registry.
	// (GET /instruments)
	ListInstruments(ctx context.Context, request ListInstrumentsRequestObject) (ListInstrumentsResponseObject, error)
	// GetInstrument Identity, grade, decoded prerogatives with their sentences, the live multiplier and the field it came from, unknown extensions, and the capture slot.
	// (GET /instruments/{mint})
	GetInstrument(ctx context.Context, request GetInstrumentRequestObject) (GetInstrumentResponseObject, error)
	// GetInstrumentAdmissibility The policy decision for this instrument, with reasons, version and digest.
	// (GET /instruments/{mint}/admissibility)
	GetInstrumentAdmissibility(ctx context.Context, request GetInstrumentAdmissibilityRequestObject) (GetInstrumentAdmissibilityResponseObject, error)
	// GetInstrumentDepth Depth at size as a curve, with each quote's age and expiry. Selling reports unavailable until it is measured (docs/prd/API.md 5.1).
	// (GET /instruments/{mint}/depth)
	GetInstrumentDepth(ctx context.Context, request GetInstrumentDepthRequestObject) (GetInstrumentDepthResponseObject, error)
	// GetPolicy A policy document, as data (server/internal/policy.Document).
	// (GET /policies/{version})
	GetPolicy(ctx context.Context, request GetPolicyRequestObject) (GetPolicyResponseObject, error)
	// ListReasonCodes Every reason code and its fixed meaning.
	// (GET /reason-codes)
	ListReasonCodes(ctx context.Context, request ListReasonCodesRequestObject) (ListReasonCodesResponseObject, error)
	// GetReceipt The public body, its inclusion proof, its batch root and the anchor transaction. Shaped so the verification ritual needs nothing else (docs/prd/EXPLORER.md section 3.1).
	// (GET /receipts/{serial})
	GetReceipt(ctx context.Context, request GetReceiptRequestObject) (GetReceiptResponseObject, error)
	// GetStatus Seametry's own freshness: ledger lag, observer age per instrument and source, seal backlog, in the same evidence shape as any source.
	// (GET /status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// StreamEvents Public live change over server-sent events (docs/prd/API.md section 6).
	// (GET /stream)
	StreamEvents(ctx context.Context, request StreamEventsRequestObject) (StreamEventsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAlloys operation middleware
func (sh *strictHandler) ListAlloys(w http.ResponseWriter, r *http.Request, params ListAlloysParams) {
	var request ListAlloysRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAlloys(ctx, request.(ListAlloysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAlloys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAlloysResponseObject); ok {
		if err := validResponse.VisitListAlloysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlloy operation middleware
func (sh *strictHandler) GetAlloy(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyParams) {
	var request GetAlloyRequestObject

	request.Address = address
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlloy(ctx, request.(GetAlloyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlloy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlloyResponseObject); ok {
		if err := validResponse.VisitGetAlloyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlloyMeltProceeds operation middleware
func (sh *strictHandler) GetAlloyMeltProceeds(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyMeltProceedsParams) {
	var request GetAlloyMeltProceedsRequestObject

	request.Address = address
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlloyMeltProceeds(ctx, request.(GetAlloyMeltProceedsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlloyMeltProceeds")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlloyMeltProceedsResponseObject); ok {
		if err := validResponse.VisitGetAlloyMeltProceedsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlloyNav operation middleware
func (sh *strictHandler) GetAlloyNav(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyNavParams) {
	var request GetAlloyNavRequestObject

	request.Address = address
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlloyNav(ctx, request.(GetAlloyNavRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlloyNav")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlloyNavResponseObject); ok {
		if err := validResponse.VisitGetAlloyNavResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlloyStrikeCost operation middleware
func (sh *strictHandler) GetAlloyStrikeCost(w http.ResponseWriter, r *http.Request, address AlloyAddress, params GetAlloyStrikeCostParams) {
	var request GetAlloyStrikeCostRequestObject

	request.Address = address
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlloyStrikeCost(ctx, request.(GetAlloyStrikeCostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlloyStrikeCost")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlloyStrikeCostResponseObject); ok {
		if err := validResponse.VisitGetAlloyStrikeCostResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAnchorKeys operation middleware
func (sh *strictHandler) ListAnchorKeys(w http.ResponseWriter, r *http.Request) {
	var request ListAnchorKeysRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAnchorKeys(ctx, request.(ListAnchorKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAnchorKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAnchorKeysResponseObject); ok {
		if err := validResponse.VisitListAnchorKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBatch operation middleware
func (sh *strictHandler) GetBatch(w http.ResponseWriter, r *http.Request, root string) {
	var request GetBatchRequestObject

	request.Root = root

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBatch(ctx, request.(GetBatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBatch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBatchResponseObject); ok {
		if err := validResponse.VisitGetBatchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFindings operation middleware
func (sh *strictHandler) ListFindings(w http.ResponseWriter, r *http.Request) {
	var request ListFindingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFindings(ctx, request.(ListFindingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFindings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFindingsResponseObject); ok {
		if err := validResponse.VisitListFindingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFinding operation middleware
func (sh *strictHandler) GetFinding(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetFindingRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFinding(ctx, request.(GetFindingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFinding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFindingResponseObject); ok {
		if err := validResponse.VisitGetFindingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EvaluateFormula operation middleware
func (sh *strictHandler) EvaluateFormula(w http.ResponseWriter, r *http.Request) {
	var request EvaluateFormulaRequestObject

	var body EvaluateFormulaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EvaluateFormula(ctx, request.(EvaluateFormulaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EvaluateFormula")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateFormulaResponseObject); ok {
		if err := validResponse.VisitEvaluateFormulaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHallDemonstration operation middleware
func (sh *strictHandler) GetHallDemonstration(w http.ResponseWriter, r *http.Request, params GetHallDemonstrationParams) {
	var request GetHallDemonstrationRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHallDemonstration(ctx, request.(GetHallDemonstrationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHallDemonstration")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHallDemonstrationResponseObject); ok {
		if err := validResponse.VisitGetHallDemonstrationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInstruments operation middleware
func (sh *strictHandler) ListInstruments(w http.ResponseWriter, r *http.Request, params ListInstrumentsParams) {
	var request ListInstrumentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstruments(ctx, request.(ListInstrumentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstruments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstrumentsResponseObject); ok {
		if err := validResponse.VisitListInstrumentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstrument operation middleware
func (sh *strictHandler) GetInstrument(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentParams) {
	var request GetInstrumentRequestObject

	request.Mint = mint
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstrument(ctx, request.(GetInstrumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstrument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstrumentResponseObject); ok {
		if err := validResponse.VisitGetInstrumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstrumentAdmissibility operation middleware
func (sh *strictHandler) GetInstrumentAdmissibility(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentAdmissibilityParams) {
	var request GetInstrumentAdmissibilityRequestObject

	request.Mint = mint
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstrumentAdmissibility(ctx, request.(GetInstrumentAdmissibilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstrumentAdmissibility")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstrumentAdmissibilityResponseObject); ok {
		if err := validResponse.VisitGetInstrumentAdmissibilityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstrumentDepth operation middleware
func (sh *strictHandler) GetInstrumentDepth(w http.ResponseWriter, r *http.Request, mint Mint, params GetInstrumentDepthParams) {
	var request GetInstrumentDepthRequestObject

	request.Mint = mint
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstrumentDepth(ctx, request.(GetInstrumentDepthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstrumentDepth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstrumentDepthResponseObject); ok {
		if err := validResponse.VisitGetInstrumentDepthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPolicy operation middleware
func (sh *strictHandler) GetPolicy(w http.ResponseWriter, r *http.Request, version PolicyVersion) {
	var request GetPolicyRequestObject

	request.Version = version

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPolicy(ctx, request.(GetPolicyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPolicy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPolicyResponseObject); ok {
		if err := validResponse.VisitGetPolicyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReasonCodes operation middleware
func (sh *strictHandler) ListReasonCodes(w http.ResponseWriter, r *http.Request) {
	var request ListReasonCodesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListReasonCodes(ctx, request.(ListReasonCodesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReasonCodes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReasonCodesResponseObject); ok {
		if err := validResponse.VisitListReasonCodesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReceipt operation middleware
func (sh *strictHandler) GetReceipt(w http.ResponseWriter, r *http.Request, serial string) {
	var request GetReceiptRequestObject

	request.Serial = serial

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReceipt(ctx, request.(GetReceiptRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReceipt")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReceiptResponseObject); ok {
		if err := validResponse.VisitGetReceiptResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamEvents operation middleware
func (sh *strictHandler) StreamEvents(w http.ResponseWriter, r *http.Request, params StreamEventsParams) {
	var request StreamEventsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamEvents(ctx, request.(StreamEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamEventsResponseObject); ok {
		if err := validResponse.VisitStreamEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
