// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for DecisionDecision.
const (
	DecisionDecisionALLOW DecisionDecision = "ALLOW"
	DecisionDecisionBLOCK DecisionDecision = "BLOCK"
	DecisionDecisionWARN  DecisionDecision = "WARN"
)

// Valid indicates whether the value is a known member of the DecisionDecision enum.
func (e DecisionDecision) Valid() bool {
	switch e {
	case DecisionDecisionALLOW:
		return true
	case DecisionDecisionBLOCK:
		return true
	case DecisionDecisionWARN:
		return true
	default:
		return false
	}
}

// Defines values for DepthPointAvailability.
const (
	DepthPointAvailabilityAvailable   DepthPointAvailability = "available"
	DepthPointAvailabilityUnavailable DepthPointAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the DepthPointAvailability enum.
func (e DepthPointAvailability) Valid() bool {
	switch e {
	case DepthPointAvailabilityAvailable:
		return true
	case DepthPointAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HallMoveResult.
const (
	Ok      HallMoveResult = "ok"
	Refused HallMoveResult = "refused"
)

// Valid indicates whether the value is a known member of the HallMoveResult enum.
func (e HallMoveResult) Valid() bool {
	switch e {
	case Ok:
		return true
	case Refused:
		return true
	default:
		return false
	}
}

// Defines values for HallProducerKind.
const (
	HallProducerKindDevnet  HallProducerKind = "devnet"
	HallProducerKindLitesvm HallProducerKind = "litesvm"
)

// Valid indicates whether the value is a known member of the HallProducerKind enum.
func (e HallProducerKind) Valid() bool {
	switch e {
	case HallProducerKindDevnet:
		return true
	case HallProducerKindLitesvm:
		return true
	default:
		return false
	}
}

// Defines values for MetaCluster.
const (
	MetaClusterDevnet  MetaCluster = "devnet"
	MetaClusterMainnet MetaCluster = "mainnet"
)

// Valid indicates whether the value is a known member of the MetaCluster enum.
func (e MetaCluster) Valid() bool {
	switch e {
	case MetaClusterDevnet:
		return true
	case MetaClusterMainnet:
		return true
	default:
		return false
	}
}

// Defines values for MetaCompleteness.
const (
	Complete MetaCompleteness = "complete"
	Partial  MetaCompleteness = "partial"
)

// Valid indicates whether the value is a known member of the MetaCompleteness enum.
func (e MetaCompleteness) Valid() bool {
	switch e {
	case Complete:
		return true
	case Partial:
		return true
	default:
		return false
	}
}

// Defines values for MissingPartState.
const (
	MissingPartStatePruned      MissingPartState = "pruned"
	MissingPartStateStale       MissingPartState = "stale"
	MissingPartStateUnavailable MissingPartState = "unavailable"
)

// Valid indicates whether the value is a known member of the MissingPartState enum.
func (e MissingPartState) Valid() bool {
	switch e {
	case MissingPartStatePruned:
		return true
	case MissingPartStateStale:
		return true
	case MissingPartStateUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ProofStepSide.
const (
	Left  ProofStepSide = "left"
	Right ProofStepSide = "right"
)

// Valid indicates whether the value is a known member of the ProofStepSide enum.
func (e ProofStepSide) Valid() bool {
	switch e {
	case Left:
		return true
	case Right:
		return true
	default:
		return false
	}
}

// Defines values for ReasonSeverity.
const (
	ReasonSeverityALLOW ReasonSeverity = "ALLOW"
	ReasonSeverityBLOCK ReasonSeverity = "BLOCK"
	ReasonSeverityWARN  ReasonSeverity = "WARN"
)

// Valid indicates whether the value is a known member of the ReasonSeverity enum.
func (e ReasonSeverity) Valid() bool {
	switch e {
	case ReasonSeverityALLOW:
		return true
	case ReasonSeverityBLOCK:
		return true
	case ReasonSeverityWARN:
		return true
	default:
		return false
	}
}

// Defines values for ResolvedMultiplierSource.
const (
	Multiplier    ResolvedMultiplierSource = "multiplier"
	NewMultiplier ResolvedMultiplierSource = "new_multiplier"
)

// Valid indicates whether the value is a known member of the ResolvedMultiplierSource enum.
func (e ResolvedMultiplierSource) Valid() bool {
	switch e {
	case Multiplier:
		return true
	case NewMultiplier:
		return true
	default:
		return false
	}
}

// Defines values for StatusReportSourcesEvidenceState.
const (
	StatusReportSourcesEvidenceStateStale       StatusReportSourcesEvidenceState = "stale"
	StatusReportSourcesEvidenceStateUnavailable StatusReportSourcesEvidenceState = "unavailable"
	StatusReportSourcesEvidenceStateUnverified  StatusReportSourcesEvidenceState = "unverified"
	StatusReportSourcesEvidenceStateVerified    StatusReportSourcesEvidenceState = "verified"
)

// Valid indicates whether the value is a known member of the StatusReportSourcesEvidenceState enum.
func (e StatusReportSourcesEvidenceState) Valid() bool {
	switch e {
	case StatusReportSourcesEvidenceStateStale:
		return true
	case StatusReportSourcesEvidenceStateUnavailable:
		return true
	case StatusReportSourcesEvidenceStateUnverified:
		return true
	case StatusReportSourcesEvidenceStateVerified:
		return true
	default:
		return false
	}
}

// Defines values for GetHallDemonstrationParamsCluster.
const (
	GetHallDemonstrationParamsClusterDevnet    GetHallDemonstrationParamsCluster = "devnet"
	GetHallDemonstrationParamsClusterSimulator GetHallDemonstrationParamsCluster = "simulator"
)

// Valid indicates whether the value is a known member of the GetHallDemonstrationParamsCluster enum.
func (e GetHallDemonstrationParamsCluster) Valid() bool {
	switch e {
	case GetHallDemonstrationParamsClusterDevnet:
		return true
	case GetHallDemonstrationParamsClusterSimulator:
		return true
	default:
		return false
	}
}

// Defines values for GetInstrumentDepthParamsDirection.
const (
	Buy  GetInstrumentDepthParamsDirection = "buy"
	Sell GetInstrumentDepthParamsDirection = "sell"
)

// Valid indicates whether the value is a known member of the GetInstrumentDepthParamsDirection enum.
func (e GetInstrumentDepthParamsDirection) Valid() bool {
	switch e {
	case Buy:
		return true
	case Sell:
		return true
	default:
		return false
	}
}

// Amount Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3).
type Amount struct {
	// Atoms Integer atoms, as a decimal string.
	Atoms string `json:"atoms"`
	Scale int    `json:"scale"`
}

// AnchorKey defines model for AnchorKey.
type AnchorKey struct {
	ActiveFrom time.Time `json:"active_from"`

	// ActiveTo Absent for the currently active key.
	ActiveTo *time.Time `json:"active_to,omitempty"`
	Key      string     `json:"key"`
}

// Batch defines model for Batch.
type Batch struct {
	Anchor *struct {
		Cluster     *string `json:"cluster,omitempty"`
		Transaction *string `json:"transaction,omitempty"`
	} `json:"anchor,omitempty"`
	Leaves []struct {
		PublicDigest string `json:"public_digest"`
		Serial       string `json:"serial"`
	} `json:"leaves"`
	Root string `json:"root"`
}

// CostRow What a strike takes or a melt returns, per leg, at one share count.
type CostRow struct {
	Legs []struct {
		// Amount Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3).
		Amount Amount `json:"amount"`

		// Kept Present on melt-proceeds only: what the Hall keeps to rounding.
		Kept  *Amount `json:"kept,omitempty"`
		Stock string  `json:"stock"`
	} `json:"legs"`
	Shares string `json:"shares"`
}

// Decision defines model for Decision.
type Decision struct {
	Decision DecisionDecision `json:"decision"`

	// ExpiresAt Populated by the gateway, per SERVICE_CATALOG.md section 3.5's documented output shape. internal/policy's own Result does not carry this field yet; it is specified here ahead of that.
	ExpiresAt     *time.Time `json:"expires_at,omitempty"`
	InputDigest   string     `json:"input_digest"`
	PolicyVersion string     `json:"policy_version"`
	Reasons       []Reason   `json:"reasons"`
}

// DecisionDecision defines model for Decision.Decision.
type DecisionDecision string

// DepthCurve defines model for DepthCurve.
type DepthCurve struct {
	Points []DepthPoint `json:"points"`

	// ReferenceIndex -1 when no size priced.
	ReferenceIndex int `json:"reference_index"`
}

// DepthPoint defines model for DepthPoint.
type DepthPoint struct {
	Availability DepthPointAvailability `json:"availability"`
	ProviderCode *string                `json:"provider_code,omitempty"`

	// ShortfallBps Absent when there is no quote here or no reference to compare against.
	ShortfallBps *int `json:"shortfall_bps,omitempty"`

	// Size Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3).
	Size Amount `json:"size"`
}

// DepthPointAvailability defines model for DepthPoint.Availability.
type DepthPointAvailability string

// Finding defines model for Finding.
type Finding struct {
	DoesNotEstablish []string   `json:"does_not_establish"`
	PublishedAt      *time.Time `json:"published_at,omitempty"`

	// ReproduceWith The one command a visitor runs to reproduce it.
	ReproduceWith string `json:"reproduce_with"`
	Slug          string `json:"slug"`
	Summary       string `json:"summary"`
	Title         string `json:"title"`
}

// HallHolderView defines model for HallHolderView.
type HallHolderView struct {
	Claims        []string `json:"claims"`
	Shares        string   `json:"shares"`
	StockBalances []string `json:"stock_balances"`
}

// HallLegState defines model for HallLegState.
type HallLegState struct {
	HallBalance string `json:"hall_balance"`
	Ledger      string `json:"ledger"`
	Pending     string `json:"pending"`
	Stock       string `json:"stock"`
	Unclaimed   string `json:"unclaimed"`
}

// HallMove defines model for HallMove.
type HallMove struct {
	Action string `json:"action"`
	Actor  string `json:"actor"`

	// Reason Present only when result is refused.
	Reason *string        `json:"reason,omitempty"`
	Result HallMoveResult `json:"result"`

	// Signature Present only on a devnet run, and only for a step that landed.
	Signature *string    `json:"signature,omitempty"`
	State     *HallState `json:"state,omitempty"`
}

// HallMoveResult defines model for HallMove.Result.
type HallMoveResult string

// HallProducer defines model for HallProducer.
type HallProducer struct {
	// Cluster Absent for a simulator run.
	Cluster     *string          `json:"cluster,omitempty"`
	Description string           `json:"description"`
	Kind        HallProducerKind `json:"kind"`
	ProgramId   string           `json:"program_id"`
	Signatures  bool             `json:"signatures"`
}

// HallProducerKind defines model for HallProducer.Kind.
type HallProducerKind string

// HallScene defines model for HallScene.
type HallScene struct {
	DoesNotShow string     `json:"does_not_show"`
	Id          string     `json:"id"`
	Shows       string     `json:"shows"`
	Steps       []HallMove `json:"steps"`
	Title       string     `json:"title"`
}

// HallState defines model for HallState.
type HallState struct {
	Holder HallHolderView `json:"holder"`
	Legs   []HallLegState `json:"legs"`
	Supply string         `json:"supply"`
}

// HallTranscript The shape server/cmd/explorer/hall.go decodes today, published at this contract's field names (docs/prd/HALL.md section 7).
type HallTranscript struct {
	NotShown  []string     `json:"not_shown"`
	Note      string       `json:"note"`
	Producer  HallProducer `json:"producer"`
	Scenarios []HallScene  `json:"scenarios"`
}

// Instrument defines model for Instrument.
type Instrument struct {
	Capture struct {
		CapturedAt *time.Time `json:"captured_at,omitempty"`
		Commitment *string    `json:"commitment,omitempty"`
		Slot       string     `json:"slot"`
	} `json:"capture"`

	// Grade The legal shape of the claim. Never a quality judgment.
	Grade string `json:"grade"`
	Mint  string `json:"mint"`

	// Multiplier The live Scaled UI multiplier and the evidence for it (registry.ResolvedMultiplier).
	Multiplier   *ResolvedMultiplier `json:"multiplier,omitempty"`
	Prerogatives []Prerogative       `json:"prerogatives"`
	Quarantined  *bool               `json:"quarantined,omitempty"`
	Symbol       *string             `json:"symbol,omitempty"`

	// UnknownExtensions Named by number, never dropped.
	UnknownExtensions []int `json:"unknown_extensions"`
}

// Meta The outer envelope every response carries (docs/prd/API.md section 4.3).
type Meta struct {
	AsOf time.Time `json:"as_of"`

	// Cluster Named wherever chain state is involved.
	Cluster      *MetaCluster     `json:"cluster,omitempty"`
	Completeness MetaCompleteness `json:"completeness"`
	Missing      *[]MissingPart   `json:"missing,omitempty"`
	ServedAt     time.Time        `json:"served_at"`
}

// MetaCluster Named wherever chain state is involved.
type MetaCluster string

// MetaCompleteness defines model for Meta.Completeness.
type MetaCompleteness string

// MissingPart defines model for MissingPart.
type MissingPart struct {
	Part string `json:"part"`

	// Reason A stable reason code.
	Reason string           `json:"reason"`
	State  MissingPartState `json:"state"`
}

// MissingPartState defines model for MissingPart.State.
type MissingPartState string

// Prerogative One decoded issuer power, as a plain sentence (registry.Prerogatives.Sentences; docs/prd/EXPLORER.md section 3.2).
type Prerogative struct {
	// ExtensionNumber Present only for an unrecognised extension.
	ExtensionNumber *int   `json:"extension_number,omitempty"`
	Sentence        string `json:"sentence"`
}

// Problem RFC 9457.
type Problem struct {
	// Detail Names the value, the expectation, and where it came from.
	Detail string `json:"detail"`
	Status int    `json:"status"`
	Title  string `json:"title"`
	Type   string `json:"type"`
}

// Proof defines model for Proof.
type Proof struct {
	// Anchor Absent until a batch root is anchored on chain.
	Anchor *struct {
		Cluster     *string `json:"cluster,omitempty"`
		Transaction *string `json:"transaction,omitempty"`
	} `json:"anchor,omitempty"`
	Path []ProofStep `json:"path"`

	// PrivateCommitment The private body's digest, never the body.
	PrivateCommitment string `json:"private_commitment"`

	// PublicBody receipt.PublicBody. Never a signature, a wallet, or an exact amount.
	PublicBody ReceiptPublic `json:"public_body"`
	Root       string        `json:"root"`
	Serial     string        `json:"serial"`
}

// ProofStep defines model for ProofStep.
type ProofStep struct {
	Hash string        `json:"hash"`
	Side ProofStepSide `json:"side"`
}

// ProofStepSide defines model for ProofStep.Side.
type ProofStepSide string

// Reason defines model for Reason.
type Reason struct {
	Code string `json:"code"`

	// Fact Describes; never advises.
	Fact     string         `json:"fact"`
	Severity ReasonSeverity `json:"severity"`
}

// ReasonSeverity defines model for Reason.Severity.
type ReasonSeverity string

// ReceiptPublic receipt.PublicBody. Never a signature, a wallet, or an exact amount.
type ReceiptPublic struct {
	Basket       string `json:"basket"`
	Constituents []struct {
		Grade     string   `json:"grade"`
		IssuerCan []string `json:"issuer_can"`
		Mint      string   `json:"mint"`
		Ticker    string   `json:"ticker"`
	} `json:"constituents"`
	Kind            string    `json:"kind"`
	Month           string    `json:"month"`
	Office          string    `json:"office"`
	PolicyVersion   string    `json:"policy_version"`
	Serial          string    `json:"serial"`
	Settlement      string    `json:"settlement"`
	SizeBand        string    `json:"size_band"`
	Venues          *[]string `json:"venues,omitempty"`
	WeakestEvidence string    `json:"weakest_evidence"`
}

// ResolvedMultiplier The live Scaled UI multiplier and the evidence for it (registry.ResolvedMultiplier).
type ResolvedMultiplier struct {
	ActivationPending bool      `json:"activation_pending"`
	EffectiveAt       time.Time `json:"effective_at"`
	NaiveIsStale      bool      `json:"naive_is_stale"`

	// NaiveValue What reading the field named multiplier alone would give.
	NaiveValue Amount                   `json:"naive_value"`
	Source     ResolvedMultiplierSource `json:"source"`

	// Value Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3).
	Value Amount `json:"value"`
}

// ResolvedMultiplierSource defines model for ResolvedMultiplier.Source.
type ResolvedMultiplierSource string

// StatusReport defines model for StatusReport.
type StatusReport struct {
	LedgerLagSeconds int  `json:"ledger_lag_seconds"`
	SealBacklog      *int `json:"seal_backlog,omitempty"`
	Sources          []struct {
		AgeSeconds    *int                             `json:"age_seconds,omitempty"`
		EvidenceState StatusReportSourcesEvidenceState `json:"evidence_state"`
		Source        string                           `json:"source"`
	} `json:"sources"`
}

// StatusReportSourcesEvidenceState defines model for StatusReport.Sources.EvidenceState.
type StatusReportSourcesEvidenceState string

// AlloyAddress defines model for AlloyAddress.
type AlloyAddress = string

// AsOf defines model for AsOf.
type AsOf = time.Time

// Cursor defines model for Cursor.
type Cursor = string

// Mint defines model for Mint.
type Mint = string

// Shares defines model for Shares.
type Shares = string

// GetAlloyMeltProceedsParams defines parameters for GetAlloyMeltProceeds.
type GetAlloyMeltProceedsParams struct {
	// Shares A share count, as a string since it may exceed 2^53 (docs/prd/API.md section 4.1).
	Shares Shares `form:"shares" json:"shares"`
}

// GetAlloyStrikeCostParams defines parameters for GetAlloyStrikeCost.
type GetAlloyStrikeCostParams struct {
	// Shares A share count, as a string since it may exceed 2^53 (docs/prd/API.md section 4.1).
	Shares Shares `form:"shares" json:"shares"`
}

// GetHallDemonstrationParams defines parameters for GetHallDemonstration.
type GetHallDemonstrationParams struct {
	Cluster GetHallDemonstrationParamsCluster `form:"cluster" json:"cluster"`
}

// GetHallDemonstrationParamsCluster defines parameters for GetHallDemonstration.
type GetHallDemonstrationParamsCluster string

// ListInstrumentsParams defines parameters for ListInstruments.
type ListInstrumentsParams struct {
	// AsOf What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5).
	AsOf *AsOf `form:"as_of,omitempty" json:"as_of,omitempty"`

	// Cursor An opaque cursor from a previous page.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetInstrumentParams defines parameters for GetInstrument.
type GetInstrumentParams struct {
	// AsOf What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5).
	AsOf *AsOf `form:"as_of,omitempty" json:"as_of,omitempty"`
}

// GetInstrumentAdmissibilityParams defines parameters for GetInstrumentAdmissibility.
type GetInstrumentAdmissibilityParams struct {
	// AsOf What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5).
	AsOf *AsOf `form:"as_of,omitempty" json:"as_of,omitempty"`
}

// GetInstrumentDepthParams defines parameters for GetInstrumentDepth.
type GetInstrumentDepthParams struct {
	Direction *GetInstrumentDepthParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
}

// GetInstrumentDepthParamsDirection defines parameters for GetInstrumentDepth.
type GetInstrumentDepthParamsDirection string
