/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every instrument in the registry. */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity, grade, decoded prerogatives with their sentences, the live multiplier and the field it came from, unknown extensions, and the capture slot. */
        get: operations["getInstrument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}/admissibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The policy decision for this instrument, with reasons, version and digest. */
        get: operations["getInstrumentAdmissibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Depth at size as a curve, with each quote's age and expiry. Selling reports unavailable until it is measured (docs/prd/API.md 5.1). */
        get: operations["getInstrumentDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every published finding a visitor can reproduce by running one command. */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One finding, with what it does not establish stated beside it. */
        get: operations["getFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hall/demonstration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The demonstration transcript for one cluster: every scenario, its steps, actors, results, reasons, and, on devnet, transaction signatures. docs/prd/HALL.md section 7. */
        get: operations["getHallDemonstration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every alloy, read from chain. */
        get: operations["listAlloys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An alloy's recipe, supply, each leg's ledger, pending and unclaimed balances, and held-back legs (chain/programs/hall/src/state.rs::Alloy, with held_back derived by checking each leg's own account for a freeze, since the program stores no such flag). */
        get: operations["getAlloy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Off-chain NAV against share price. Until an oracle read and a share pool exist (docs/prd/API.md section 14) this always answers completeness: partial, with missing parts nav (NAV_NO_PRICE_SOURCE) and share_price (SHARE_PRICE_NO_POOL), never a placeholder figure. */
        get: operations["getAlloyNav"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}/strike-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a strike of n shares takes per leg, rounded up. */
        get: operations["getAlloyStrikeCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}/melt-proceeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a melt of n shares returns per leg, rounded down, and what the Hall keeps. */
        get: operations["getAlloyMeltProceeds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/formulas/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admissibility, required atoms and stored depth for a formula not yet on chain, per leg, at most MAX_CONSTITUENTS (12, chain/programs/hall/src/state.rs).
         * @description required_atoms is an exact units_per_share * shares, never basket.RequiredIn or basket.Out (server/internal/basket/recipe.go): those round a ratio between an existing ledger and supply, which a formula not yet struck does not have. Strike and melt need the same atoms here. A live buy quote is attached per leg where the shared Jupiter budget (docs/prd/API.md section 12, step A2) allows one; a total_quote is produced only when every leg carries an unexpired quote, and it is summed here, never by a client (section 2, rule 4).
         */
        post: operations["evaluateFormula"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A policy document, as data (server/internal/policy.Document). */
        get: operations["getPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reason-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every reason code and its fixed meaning.
         * @description A client must show a code it does not recognise, never map it to one it does (docs/prd/API.md section 4.7). This resource is how a client gets the meaning of a code it does not yet know.
         */
        get: operations["listReasonCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public live change over server-sent events (docs/prd/API.md section 6).
         * @description GET /v1/me/stream, which adds the account's own events, is specified alongside identity (docs/prd/API.md section 12, step A6), not here.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The public body, its inclusion proof, its batch root and the anchor transaction. Shaped so the verification ritual needs nothing else (docs/prd/EXPLORER.md section 3.1). */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{root}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A sealed batch, its leaves' public digests and its anchor. */
        get: operations["getBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anchor-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published list of keys allowed to anchor a root, with rotation dates. */
        get: operations["listAnchorKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seametry's own freshness: ledger lag, observer age per instrument and source, seal backlog, in the same evidence shape as any source. */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The opaque account subject accepted by the Go core. */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountSubject: {
            /** @description The opaque Better Auth account subject. No profile field is carried in the service token. */
            id: string;
        };
        /** @description Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3). */
        Amount: {
            /**
             * @description Integer atoms, as a decimal string.
             * @example 1000000
             */
            atoms: string;
            /** @example 6 */
            scale: number;
        };
        /** @description A value that came from outside Seametry, or was computed from something that did (docs/prd/API.md section 4.2). */
        Observation: {
            /** @description Absent when evidence_state is unavailable. */
            value?: components["schemas"]["Amount"];
            /** @example solana:mainnet:getAccountInfo */
            source: string;
            /** Format: date-time */
            source_event_at: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            persisted_at: string;
            /** @description A slot number, as a string since it may exceed 2^53. */
            slot?: string;
            /** @enum {string} */
            evidence_state: "verified" | "unverified" | "stale" | "unavailable" | "pruned";
            /** @description Derived at read time against the served time, never stored. */
            age_seconds?: number;
            /** @description The content address (sha256:...) of the payload this value was derived from. */
            raw?: string;
        };
        /** @description The outer envelope every response carries (docs/prd/API.md section 4.3). */
        Meta: {
            /** Format: date-time */
            served_at: string;
            /** Format: date-time */
            as_of: string;
            /** @enum {string} */
            completeness: "complete" | "partial";
            missing?: components["schemas"]["MissingPart"][];
            /**
             * @description Named wherever chain state is involved.
             * @enum {string}
             */
            cluster?: "devnet" | "mainnet";
        };
        MissingPart: {
            part: string;
            /** @enum {string} */
            state: "unavailable" | "stale" | "pruned";
            /** @description A stable reason code. */
            reason: string;
        };
        /** @description RFC 9457. */
        Problem: {
            type: string;
            title: string;
            status: number;
            /** @description Names the value, the expectation, and where it came from. */
            detail: string;
        };
        /** @description A base58 Solana address, or null when the authority is absent. */
        Pubkey: string;
        /** @description One decoded issuer power, as a plain sentence (registry.Prerogatives.Sentences; docs/prd/EXPLORER.md section 3.2). */
        Prerogative: {
            sentence: string;
            /** @description Present only for an unrecognised extension. */
            extension_number?: number;
        };
        /** @description The live Scaled UI multiplier and the evidence for it (registry.ResolvedMultiplier). */
        ResolvedMultiplier: {
            value: components["schemas"]["Amount"];
            /** @enum {string} */
            source: "multiplier" | "new_multiplier";
            /** Format: date-time */
            effective_at: string;
            activation_pending: boolean;
            /** @description What reading the field named multiplier alone would give. */
            naive_value: components["schemas"]["Amount"];
            naive_is_stale: boolean;
        };
        Instrument: {
            mint: string;
            symbol?: string;
            /** @description The legal shape of the claim. Never a quality judgment. */
            grade: string;
            prerogatives: components["schemas"]["Prerogative"][];
            multiplier?: components["schemas"]["ResolvedMultiplier"];
            /** @description Named by number, never dropped. */
            unknown_extensions: number[];
            quarantined?: boolean;
            capture: {
                slot: string;
                commitment?: string;
                /** Format: date-time */
                captured_at?: string;
            };
        };
        Decision: {
            /** @enum {string} */
            decision: "ALLOW" | "WARN" | "BLOCK";
            reasons: components["schemas"]["Reason"][];
            policy_version: string;
            input_digest: string;
            /**
             * Format: date-time
             * @description Populated by the gateway, per SERVICE_CATALOG.md section 3.5's documented output shape. internal/policy's own Result does not carry this field yet; it is specified here ahead of that.
             */
            expires_at?: string;
        };
        Reason: {
            code: string;
            /** @enum {string} */
            severity: "ALLOW" | "WARN" | "BLOCK";
            /** @description Describes; never advises. */
            fact: string;
        };
        DepthCurve: {
            points: components["schemas"]["DepthPoint"][];
            /** @description -1 when no size priced. */
            reference_index: number;
        };
        DepthPoint: {
            size: components["schemas"]["Amount"];
            /** @enum {string} */
            availability: "available" | "unavailable";
            provider_code?: string;
            /** @description Absent when there is no quote here or no reference to compare against. */
            shortfall_bps?: number;
            /**
             * Format: date-time
             * @description When this quote was captured (liquidity.Quote.ReceivedAt). Present only when availability is available. Added so this schema actually carries what docs/prd/API.md section 5.1 and docs/prd/TERMINAL.md section 2 already promise ("each quote's age and expiry"); it did not until this field was added.
             */
            received_at?: string;
            /**
             * Format: date-time
             * @description Past this instant the quote cannot be acted on (liquidity.Quote.ExpiresAt).
             */
            expires_at?: string;
            /** @description Derived at read time against the served time, never stored. */
            age_seconds?: number;
        };
        Finding: {
            slug: string;
            title: string;
            summary: string;
            /** @description The one command a visitor runs to reproduce it. */
            reproduce_with: string;
            does_not_establish: string[];
            /** Format: date-time */
            published_at?: string;
        };
        /** @description The shape server/cmd/explorer/hall.go decodes today, published at this contract's field names (docs/prd/HALL.md section 7). */
        HallTranscript: {
            note: string;
            producer: components["schemas"]["HallProducer"];
            not_shown: string[];
            scenarios: components["schemas"]["HallScene"][];
        };
        HallProducer: {
            /** @enum {string} */
            kind: "litesvm" | "devnet";
            description: string;
            program_id: string;
            /** @description Absent for a simulator run. */
            cluster?: string;
            signatures: boolean;
        };
        HallScene: {
            id: string;
            title: string;
            shows: string;
            does_not_show: string;
            steps: components["schemas"]["HallMove"][];
        };
        HallMove: {
            actor: string;
            action: string;
            /** @enum {string} */
            result: "ok" | "refused";
            /** @description Present only when result is refused. */
            reason?: string;
            /** @description Present only on a devnet run, and only for a step that landed. */
            signature?: string;
            state?: components["schemas"]["HallState"];
        };
        HallState: {
            supply: string;
            legs: components["schemas"]["HallLegState"][];
            holder: components["schemas"]["HallHolderView"];
        };
        HallLegState: {
            stock: string;
            hall_balance: string;
            ledger: string;
            pending: string;
            unclaimed: string;
        };
        HallHolderView: {
            shares: string;
            claims: string[];
            stock_balances: string[];
        };
        /** @description What a strike takes or a melt returns, per leg, at one share count. */
        CostRow: {
            shares: string;
            legs: {
                stock: string;
                amount: components["schemas"]["Amount"];
                /** @description Present on melt-proceeds only: what the Hall keeps to rounding. */
                kept?: components["schemas"]["Amount"];
            }[];
        };
        /** @description An alloy read from chain (chain/programs/hall/src/state.rs::Alloy). */
        Alloy: {
            address: string;
            sponsor: string;
            /** @description Hex. Empty until the sponsor registers one (server/cmd/explorer's Hallmark sponsor mark field carries the same emptiness). */
            sponsor_mark?: string;
            share_mint: string;
            id: string;
            /** @description Shares outstanding, in share atoms. The share mint has 6 decimals (SHARE_DECIMALS, chain/programs/hall/src/state.rs), so 1000000 is one share, as every wallet shows it. */
            supply: string;
            /** @description The founding sponsor's shares in share atoms (6 decimals), unrecoverable by design (docs/BRAND_AND_WORLD.md section 5). */
            locked_genesis?: string;
            legs: components["schemas"]["AlloyLeg"][];
            /** @enum {string} */
            cluster: "devnet" | "mainnet";
            /** @description The share mint's own name, symbol and URI. The Hall gives up their update authority at founding, so they cannot change. Absent when the share mint carries no TokenMetadata, as Alloys founded before the Hall wrote it do not. */
            metadata?: components["schemas"]["MintMetadata"];
        };
        /** @description What a Token-2022 mint's TokenMetadata extension says about itself, decoded from the mint account's bytes (server/internal/registry). The URI names a document off chain, whose content its host can change; only these three fields are on chain. */
        MintMetadata: {
            name: string;
            symbol: string;
            uri: string;
        };
        /** @description One constituent's position (chain/programs/hall/src/state.rs::LegRecord). held_back is not a chain field: the program stores none, so the gateway derives it by checking whether this leg's own Hall-owned token account is frozen (Registry). */
        AlloyLeg: {
            mint: string;
            /** @description What backs outstanding shares. */
            ledger: components["schemas"]["Amount"];
            /** @description Credited but not yet vested. */
            pending: components["schemas"]["Amount"];
            /** @description Owed to holders who have melted but not withdrawn. */
            unclaimed: components["schemas"]["Amount"];
            /** Format: date-time */
            vest_start?: string;
            /** Format: date-time */
            vest_end?: string;
            /** @description The issuer currently prevents delivering this leg. */
            held_back: boolean;
            /** @description Present only when held_back is true. Never a smaller amount in its place (docs/prd/TERMINAL.md section 5). */
            held_back_reason?: string;
            /** @description The constituent mint's own name, symbol and URI, as its issuer wrote them. Absent when the mint carries no TokenMetadata. */
            metadata?: components["schemas"]["MintMetadata"];
        };
        /** @description Every field is absent until its source exists; meta.missing names why (docs/prd/API.md section 14). Never a placeholder figure. */
        Nav: {
            value?: components["schemas"]["Amount"];
            share_price?: components["schemas"]["Amount"];
            /** @description The gap between value and share_price. Never described as fair or correct (ENGINEERING_STANDARD.md section 16). */
            premium_bps?: number;
        };
        FormulaConstituent: {
            mint: string;
            /** @description Atoms of this constituent backing one share. */
            units_per_share: components["schemas"]["Amount"];
        };
        FormulaEvaluateRequest: {
            /** @description MAX_CONSTITUENTS (chain/programs/hall/src/state.rs). Over the limit is refused, naming the count and the limit. */
            constituents: components["schemas"]["FormulaConstituent"][];
            /** @description A share count, as a string (docs/prd/API.md section 4.1). */
            shares: string;
            /** @enum {string} */
            cluster?: "devnet" | "mainnet";
        };
        FormulaLeg: {
            mint: string;
            admissibility: components["schemas"]["Decision"];
            /** @description units_per_share * shares. The same value for a strike and a melt (see the operation description). */
            required_atoms: components["schemas"]["Amount"];
            depth?: components["schemas"]["DepthPoint"][];
            /** @description A live buy quote for required_atoms. Absent when unavailable; meta.missing names why. */
            quote?: components["schemas"]["Amount"];
        };
        FormulaEvaluateResult: {
            shares: string;
            legs: components["schemas"]["FormulaLeg"][];
            /** @description The sum of every leg's quote, in USDC atoms. Present only when every leg carries an unexpired quote. */
            total_quote?: components["schemas"]["Amount"];
        };
        /** @description server/internal/policy.Document, as published. */
        PolicyDocument: {
            version: string;
            accepted_grades: string[];
            allowed_hook_programs: string[];
            block_on_unknown_extension: boolean;
            block_on_issuer_halt: boolean;
            depth_reference_usdc: number;
            depth_ceiling_bps: number;
            impact_ceiling_bps: number;
        };
        /** @description One entry per server/internal/policy.Code constant. meaning is this repository's fixed sentence for the code, not the Fact text a particular decision carries. */
        ReasonCodeEntry: {
            code: string;
            meaning: string;
        };
        /** @description One outbox event (docs/SERVICE_CATALOG.md section 7). id is the outbox sequence, used as the SSE id field for Last-Event-ID resume. Per-event payload schemas are added here as each producing step lands; data stays an open object until then, never a guess at fields nobody has decided. */
        StreamEvent: {
            id: string;
            /** @enum {string} */
            event: "instrument.quarantined" | "prerogative.changed" | "corporate_action.effective" | "observation.degraded" | "divergence.crossed" | "session.changed" | "execution.settled" | "execution.deviated" | "receipt.sealed";
            /** Format: date-time */
            emitted_at: string;
            /** @description Payload shape not yet fixed; see the description above. */
            data: Record<string, never>;
        };
        /** @description receipt.PublicBody. Never a signature, a wallet, or an exact amount. */
        ReceiptPublic: {
            /** @description The sponsor's registered mark, hex, mirroring the on-chain Alloy's sponsor_mark. Empty until a mark is registered. Part of what the seal commits to, so it is always present. */
            sponsor_mark: string;
            serial: string;
            kind: string;
            month: string;
            basket: string;
            constituents: {
                ticker: string;
                mint: string;
                grade: string;
                issuer_can: string[];
            }[];
            weakest_evidence: string;
            size_band: string;
            venues?: string[];
            policy_version: string;
            settlement: string;
            office: string;
        };
        ProofStep: {
            /** @enum {string} */
            side: "left" | "right";
            hash: string;
        };
        Proof: {
            serial: string;
            public_body: components["schemas"]["ReceiptPublic"];
            /** @description The private body's digest, never the body. */
            private_commitment: string;
            path: components["schemas"]["ProofStep"][];
            root: string;
            /** @description Absent until a batch root is anchored on chain. */
            anchor?: {
                transaction?: string;
                cluster?: string;
            };
        };
        Batch: {
            root: string;
            leaves: {
                serial: string;
                public_digest: string;
            }[];
            anchor?: {
                transaction?: string;
                cluster?: string;
            };
        };
        AnchorKey: {
            key: string;
            /** Format: date-time */
            active_from: string;
            /**
             * Format: date-time
             * @description Absent for the currently active key.
             */
            active_to?: string;
        };
        StatusReport: {
            ledger_lag_seconds: number;
            seal_backlog?: number;
            sources: {
                source: string;
                /** @enum {string} */
                evidence_state: "verified" | "unverified" | "stale" | "unavailable";
                age_seconds?: number;
            }[];
        };
    };
    responses: {
        /** @description An error, as an RFC 9457 problem detail (docs/prd/API.md section 4.4). */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The mint's base58 address. */
        Mint: string;
        AlloyAddress: string;
        /** @description Share atoms at the share mint's 6 decimals (1000000 is one share), as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
        Shares: string;
        /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
        AsOf: string;
        /** @description An opaque cursor from a previous page. */
        Cursor: string;
        /** @example policy-2026.09.2 */
        PolicyVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInstruments: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
                /** @description An opaque cursor from a previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of instruments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Instrument"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrument: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instrument. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Instrument"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrumentAdmissibility: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Decision"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrumentDepth: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
                direction?: "buy" | "sell";
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The depth curve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DepthCurve"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The findings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Finding"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example multiplier-staleness */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The finding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Finding"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHallDemonstration: {
        parameters: {
            query: {
                cluster: "simulator" | "devnet";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HallTranscript"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAlloys: {
        parameters: {
            query?: {
                /** @description An opaque cursor from a previous page. */
                cursor?: components["parameters"]["Cursor"];
                cluster?: "devnet" | "mainnet";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of alloys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alloy"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloy: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The alloy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Alloy"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloyNav: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NAV against share price, or why it is not available yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Nav"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloyStrikeCost: {
        parameters: {
            query: {
                /** @description Share atoms at the share mint's 6 decimals (1000000 is one share), as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
                shares: components["parameters"]["Shares"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strike cost. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CostRow"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloyMeltProceeds: {
        parameters: {
            query: {
                /** @description Share atoms at the share mint's 6 decimals (1000000 is one share), as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
                shares: components["parameters"]["Shares"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The melt proceeds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CostRow"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    evaluateFormula: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormulaEvaluateRequest"];
            };
        };
        responses: {
            /** @description The evaluated formula. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FormulaEvaluateResult"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example policy-2026.09.2 */
                version: components["parameters"]["PolicyVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The policy document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PolicyDocument"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReasonCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reason codes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReasonCodeEntry"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resumes from this outbox sequence. A pruned point is named before resuming from the oldest retained event, rather than skipping silently. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A stream of server-sent events, one per outbox row (docs/SERVICE_CATALOG.md section 7). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 09260000005 */
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The receipt's proof. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proof"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The batch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Batch"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAnchorKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The anchor keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AnchorKey"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StatusReport"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated account boundary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AccountSubject"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
