/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every instrument in the registry. */
        get: operations["listInstruments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity, grade, decoded prerogatives with their sentences, the live multiplier and the field it came from, unknown extensions, and the capture slot. */
        get: operations["getInstrument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}/admissibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The policy decision for this instrument, with reasons, version and digest. */
        get: operations["getInstrumentAdmissibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{mint}/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Depth at size as a curve, with each quote's age and expiry. Selling reports unavailable until it is measured (docs/prd/API.md 5.1). */
        get: operations["getInstrumentDepth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every published finding a visitor can reproduce by running one command. */
        get: operations["listFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One finding, with what it does not establish stated beside it. */
        get: operations["getFinding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hall/demonstration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The demonstration transcript for one cluster: every scenario, its steps, actors, results, reasons, and, on devnet, transaction signatures. docs/prd/HALL.md section 7. */
        get: operations["getHallDemonstration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}/strike-cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a strike of n shares takes per leg, rounded up. */
        get: operations["getAlloyStrikeCost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alloys/{address}/melt-proceeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a melt of n shares returns per leg, rounded down, and what the Hall keeps. */
        get: operations["getAlloyMeltProceeds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The public body, its inclusion proof, its batch root and the anchor transaction. Shaped so the verification ritual needs nothing else (docs/prd/EXPLORER.md section 3.1). */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{root}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A sealed batch, its leaves' public digests and its anchor. */
        get: operations["getBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anchor-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published list of keys allowed to anchor a root, with rotation dates. */
        get: operations["listAnchorKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seametry's own freshness: ledger lag, observer age per instrument and source, seal backlog, in the same evidence shape as any source. */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Integer atoms plus an explicit scale. Never a JSON number (docs/prd/API.md section 4.1; ENGINEERING_STANDARD.md section 3). */
        Amount: {
            /**
             * @description Integer atoms, as a decimal string.
             * @example 1000000
             */
            atoms: string;
            /** @example 6 */
            scale: number;
        };
        /** @description A value that came from outside Seametry, or was computed from something that did (docs/prd/API.md section 4.2). */
        Observation: {
            /** @description Absent when evidence_state is unavailable. */
            value?: components["schemas"]["Amount"];
            /** @example solana:mainnet:getAccountInfo */
            source: string;
            /** Format: date-time */
            source_event_at: string;
            /** Format: date-time */
            received_at: string;
            /** Format: date-time */
            persisted_at: string;
            /** @description A slot number, as a string since it may exceed 2^53. */
            slot?: string;
            /** @enum {string} */
            evidence_state: "verified" | "unverified" | "stale" | "unavailable" | "pruned";
            /** @description Derived at read time against the served time, never stored. */
            age_seconds?: number;
            /** @description The content address (sha256:...) of the payload this value was derived from. */
            raw?: string;
        };
        /** @description The outer envelope every response carries (docs/prd/API.md section 4.3). */
        Meta: {
            /** Format: date-time */
            served_at: string;
            /** Format: date-time */
            as_of: string;
            /** @enum {string} */
            completeness: "complete" | "partial";
            missing?: components["schemas"]["MissingPart"][];
            /**
             * @description Named wherever chain state is involved.
             * @enum {string}
             */
            cluster?: "devnet" | "mainnet";
        };
        MissingPart: {
            part: string;
            /** @enum {string} */
            state: "unavailable" | "stale" | "pruned";
            /** @description A stable reason code. */
            reason: string;
        };
        /** @description RFC 9457. */
        Problem: {
            type: string;
            title: string;
            status: number;
            /** @description Names the value, the expectation, and where it came from. */
            detail: string;
        };
        /** @description A base58 Solana address, or null when the authority is absent. */
        Pubkey: string;
        /** @description One decoded issuer power, as a plain sentence (registry.Prerogatives.Sentences; docs/prd/EXPLORER.md section 3.2). */
        Prerogative: {
            sentence: string;
            /** @description Present only for an unrecognised extension. */
            extension_number?: number;
        };
        /** @description The live Scaled UI multiplier and the evidence for it (registry.ResolvedMultiplier). */
        ResolvedMultiplier: {
            value: components["schemas"]["Amount"];
            /** @enum {string} */
            source: "multiplier" | "new_multiplier";
            /** Format: date-time */
            effective_at: string;
            activation_pending: boolean;
            /** @description What reading the field named multiplier alone would give. */
            naive_value: components["schemas"]["Amount"];
            naive_is_stale: boolean;
        };
        Instrument: {
            mint: string;
            symbol?: string;
            /** @description The legal shape of the claim. Never a quality judgment. */
            grade: string;
            prerogatives: components["schemas"]["Prerogative"][];
            multiplier?: components["schemas"]["ResolvedMultiplier"];
            /** @description Named by number, never dropped. */
            unknown_extensions: number[];
            quarantined?: boolean;
            capture: {
                slot: string;
                commitment?: string;
                /** Format: date-time */
                captured_at?: string;
            };
        };
        Decision: {
            /** @enum {string} */
            decision: "ALLOW" | "WARN" | "BLOCK";
            reasons: components["schemas"]["Reason"][];
            policy_version: string;
            input_digest: string;
            /**
             * Format: date-time
             * @description Populated by the gateway, per SERVICE_CATALOG.md section 3.5's documented output shape. internal/policy's own Result does not carry this field yet; it is specified here ahead of that.
             */
            expires_at?: string;
        };
        Reason: {
            code: string;
            /** @enum {string} */
            severity: "ALLOW" | "WARN" | "BLOCK";
            /** @description Describes; never advises. */
            fact: string;
        };
        DepthCurve: {
            points: components["schemas"]["DepthPoint"][];
            /** @description -1 when no size priced. */
            reference_index: number;
        };
        DepthPoint: {
            size: components["schemas"]["Amount"];
            /** @enum {string} */
            availability: "available" | "unavailable";
            provider_code?: string;
            /** @description Absent when there is no quote here or no reference to compare against. */
            shortfall_bps?: number;
        };
        Finding: {
            slug: string;
            title: string;
            summary: string;
            /** @description The one command a visitor runs to reproduce it. */
            reproduce_with: string;
            does_not_establish: string[];
            /** Format: date-time */
            published_at?: string;
        };
        /** @description The shape server/cmd/explorer/hall.go decodes today, published at this contract's field names (docs/prd/HALL.md section 7). */
        HallTranscript: {
            note: string;
            producer: components["schemas"]["HallProducer"];
            not_shown: string[];
            scenarios: components["schemas"]["HallScene"][];
        };
        HallProducer: {
            /** @enum {string} */
            kind: "litesvm" | "devnet";
            description: string;
            program_id: string;
            /** @description Absent for a simulator run. */
            cluster?: string;
            signatures: boolean;
        };
        HallScene: {
            id: string;
            title: string;
            shows: string;
            does_not_show: string;
            steps: components["schemas"]["HallMove"][];
        };
        HallMove: {
            actor: string;
            action: string;
            /** @enum {string} */
            result: "ok" | "refused";
            /** @description Present only when result is refused. */
            reason?: string;
            /** @description Present only on a devnet run, and only for a step that landed. */
            signature?: string;
            state?: components["schemas"]["HallState"];
        };
        HallState: {
            supply: string;
            legs: components["schemas"]["HallLegState"][];
            holder: components["schemas"]["HallHolderView"];
        };
        HallLegState: {
            stock: string;
            hall_balance: string;
            ledger: string;
            pending: string;
            unclaimed: string;
        };
        HallHolderView: {
            shares: string;
            claims: string[];
            stock_balances: string[];
        };
        /** @description What a strike takes or a melt returns, per leg, at one share count. */
        CostRow: {
            shares: string;
            legs: {
                stock: string;
                amount: components["schemas"]["Amount"];
                /** @description Present on melt-proceeds only: what the Hall keeps to rounding. */
                kept?: components["schemas"]["Amount"];
            }[];
        };
        /** @description receipt.PublicBody. Never a signature, a wallet, or an exact amount. */
        ReceiptPublic: {
            serial: string;
            kind: string;
            month: string;
            basket: string;
            constituents: {
                ticker: string;
                mint: string;
                grade: string;
                issuer_can: string[];
            }[];
            weakest_evidence: string;
            size_band: string;
            venues?: string[];
            policy_version: string;
            settlement: string;
            office: string;
        };
        ProofStep: {
            /** @enum {string} */
            side: "left" | "right";
            hash: string;
        };
        Proof: {
            serial: string;
            public_body: components["schemas"]["ReceiptPublic"];
            /** @description The private body's digest, never the body. */
            private_commitment: string;
            path: components["schemas"]["ProofStep"][];
            root: string;
            /** @description Absent until a batch root is anchored on chain. */
            anchor?: {
                transaction?: string;
                cluster?: string;
            };
        };
        Batch: {
            root: string;
            leaves: {
                serial: string;
                public_digest: string;
            }[];
            anchor?: {
                transaction?: string;
                cluster?: string;
            };
        };
        AnchorKey: {
            key: string;
            /** Format: date-time */
            active_from: string;
            /**
             * Format: date-time
             * @description Absent for the currently active key.
             */
            active_to?: string;
        };
        StatusReport: {
            ledger_lag_seconds: number;
            seal_backlog?: number;
            sources: {
                source: string;
                /** @enum {string} */
                evidence_state: "verified" | "unverified" | "stale" | "unavailable";
                age_seconds?: number;
            }[];
        };
    };
    responses: {
        /** @description An error, as an RFC 9457 problem detail (docs/prd/API.md section 4.4). */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The mint's base58 address. */
        Mint: string;
        AlloyAddress: string;
        /** @description A share count, as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
        Shares: string;
        /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
        AsOf: string;
        /** @description An opaque cursor from a previous page. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInstruments: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
                /** @description An opaque cursor from a previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of instruments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Instrument"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrument: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instrument. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Instrument"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrumentAdmissibility: {
        parameters: {
            query?: {
                /** @description What Seametry held as true at this instant. Omitted means now (docs/prd/API.md section 4.5). */
                as_of?: components["parameters"]["AsOf"];
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Decision"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getInstrumentDepth: {
        parameters: {
            query?: {
                direction?: "buy" | "sell";
            };
            header?: never;
            path: {
                /** @description The mint's base58 address. */
                mint: components["parameters"]["Mint"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The depth curve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DepthCurve"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listFindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The findings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Finding"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example multiplier-staleness */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The finding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Finding"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getHallDemonstration: {
        parameters: {
            query: {
                cluster: "simulator" | "devnet";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transcript. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HallTranscript"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloyStrikeCost: {
        parameters: {
            query: {
                /** @description A share count, as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
                shares: components["parameters"]["Shares"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The strike cost. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CostRow"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAlloyMeltProceeds: {
        parameters: {
            query: {
                /** @description A share count, as a string since it may exceed 2^53 (docs/prd/API.md section 4.1). */
                shares: components["parameters"]["Shares"];
            };
            header?: never;
            path: {
                address: components["parameters"]["AlloyAddress"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The melt proceeds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CostRow"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 09260000005 */
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The receipt's proof. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proof"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                root: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The batch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Batch"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAnchorKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The anchor keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AnchorKey"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StatusReport"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
