// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package observationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ObservationObservation struct {
	ID                int64              `db:"id" json:"id"`
	SourceEventAt     pgtype.Timestamptz `db:"source_event_at" json:"source_event_at"`
	ReceivedAt        pgtype.Timestamptz `db:"received_at" json:"received_at"`
	PersistedAt       pgtype.Timestamptz `db:"persisted_at" json:"persisted_at"`
	Source            string             `db:"source" json:"source"`
	AdapterVersion    string             `db:"adapter_version" json:"adapter_version"`
	VerificationState string             `db:"verification_state" json:"verification_state"`
	RawDigest         string             `db:"raw_digest" json:"raw_digest"`
	Mint              string             `db:"mint" json:"mint"`
	RequestKey        string             `db:"request_key" json:"request_key"`
	Payload           []byte             `db:"payload" json:"payload"`
}

type ObservationRawPayload struct {
	Digest         string             `db:"digest" json:"digest"`
	Source         string             `db:"source" json:"source"`
	AdapterVersion string             `db:"adapter_version" json:"adapter_version"`
	SourceEventAt  pgtype.Timestamptz `db:"source_event_at" json:"source_event_at"`
	ReceivedAt     pgtype.Timestamptz `db:"received_at" json:"received_at"`
	PersistedAt    pgtype.Timestamptz `db:"persisted_at" json:"persisted_at"`
	ObjectKey      string             `db:"object_key" json:"object_key"`
}
