// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package observationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawPayload = `-- name: GetRawPayload :one
SELECT digest, source, adapter_version, source_event_at, received_at, persisted_at, object_key FROM observation.raw_payloads WHERE digest = $1
`

func (q *Queries) GetRawPayload(ctx context.Context, digest string) (ObservationRawPayload, error) {
	row := q.db.QueryRow(ctx, getRawPayload, digest)
	var i ObservationRawPayload
	err := row.Scan(
		&i.Digest,
		&i.Source,
		&i.AdapterVersion,
		&i.SourceEventAt,
		&i.ReceivedAt,
		&i.PersistedAt,
		&i.ObjectKey,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :one
INSERT INTO observation.observations (source_event_at, received_at, persisted_at, source, adapter_version, verification_state, raw_digest, mint, request_key, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (source, request_key, source_event_at) DO UPDATE SET raw_digest = EXCLUDED.raw_digest
RETURNING id
`

type InsertObservationParams struct {
	SourceEventAt     pgtype.Timestamptz `db:"source_event_at" json:"source_event_at"`
	ReceivedAt        pgtype.Timestamptz `db:"received_at" json:"received_at"`
	PersistedAt       pgtype.Timestamptz `db:"persisted_at" json:"persisted_at"`
	Source            string             `db:"source" json:"source"`
	AdapterVersion    string             `db:"adapter_version" json:"adapter_version"`
	VerificationState string             `db:"verification_state" json:"verification_state"`
	RawDigest         string             `db:"raw_digest" json:"raw_digest"`
	Mint              string             `db:"mint" json:"mint"`
	RequestKey        string             `db:"request_key" json:"request_key"`
	Payload           []byte             `db:"payload" json:"payload"`
}

// DO UPDATE with a no-op assignment, not DO NOTHING: RETURNING produces zero
// rows on a DO NOTHING conflict, and this query's caller (store.Ingest)
// needs the row's id whether this call inserted it or a replay already had.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.SourceEventAt,
		arg.ReceivedAt,
		arg.PersistedAt,
		arg.Source,
		arg.AdapterVersion,
		arg.VerificationState,
		arg.RawDigest,
		arg.Mint,
		arg.RequestKey,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRawPayload = `-- name: InsertRawPayload :exec
INSERT INTO observation.raw_payloads (digest, source, adapter_version, source_event_at, received_at, persisted_at, object_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (digest) DO NOTHING
`

type InsertRawPayloadParams struct {
	Digest         string             `db:"digest" json:"digest"`
	Source         string             `db:"source" json:"source"`
	AdapterVersion string             `db:"adapter_version" json:"adapter_version"`
	SourceEventAt  pgtype.Timestamptz `db:"source_event_at" json:"source_event_at"`
	ReceivedAt     pgtype.Timestamptz `db:"received_at" json:"received_at"`
	PersistedAt    pgtype.Timestamptz `db:"persisted_at" json:"persisted_at"`
	ObjectKey      string             `db:"object_key" json:"object_key"`
}

func (q *Queries) InsertRawPayload(ctx context.Context, arg InsertRawPayloadParams) error {
	_, err := q.db.Exec(ctx, insertRawPayload,
		arg.Digest,
		arg.Source,
		arg.AdapterVersion,
		arg.SourceEventAt,
		arg.ReceivedAt,
		arg.PersistedAt,
		arg.ObjectKey,
	)
	return err
}

const latestObservationForMint = `-- name: LatestObservationForMint :one
SELECT id, source_event_at, received_at, persisted_at, source, adapter_version, verification_state, raw_digest, mint, request_key, payload FROM observation.observations
WHERE mint = $1 AND source = $2
ORDER BY source_event_at DESC
LIMIT 1
`

type LatestObservationForMintParams struct {
	Mint   string `db:"mint" json:"mint"`
	Source string `db:"source" json:"source"`
}

func (q *Queries) LatestObservationForMint(ctx context.Context, arg LatestObservationForMintParams) (ObservationObservation, error) {
	row := q.db.QueryRow(ctx, latestObservationForMint, arg.Mint, arg.Source)
	var i ObservationObservation
	err := row.Scan(
		&i.ID,
		&i.SourceEventAt,
		&i.ReceivedAt,
		&i.PersistedAt,
		&i.Source,
		&i.AdapterVersion,
		&i.VerificationState,
		&i.RawDigest,
		&i.Mint,
		&i.RequestKey,
		&i.Payload,
	)
	return i, err
}
