package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// renderNote writes the human readable companion to the JSON report.
//
// Generated rather than hand written, because the two drifted apart within
// hours the first time: the survey was rerun, the issuer had added instruments,
// every count moved, and a prose file still asserted the old ones. A document
// that can disagree with its own data eventually will.
func renderNote(r report) string {
	var b strings.Builder

	pct := func(n int) string {
		if r.WithScaledUIAmount == 0 {
			return "0%"
		}
		return fmt.Sprintf("%.1f%%", 100*float64(n)/float64(r.WithScaledUIAmount))
	}
	share := func(n int) string {
		if r.MintsDecoded == 0 {
			return "0%"
		}
		return fmt.Sprintf("%.0f%%", 100*float64(n)/float64(r.MintsDecoded))
	}

	fmt.Fprintf(&b, "# What %d tokenized equities actually carry\n\n", r.MintsDecoded)
	fmt.Fprintf(&b, "**Captured %s from Solana mainnet, slot %d, via %s**\n\n",
		r.CapturedAt.Format("2 January 2006"), r.Slot, r.Cluster)
	b.WriteString("Machine readable: the JSON file beside this one.\n\n")
	b.WriteString("Reproduce it yourself, with no credentials and without asking us for anything:\n\n")
	b.WriteString("```bash\ngo run ./tools/survey\n```\n\n")
	b.WriteString("Every number below is decoded from mint account bytes by `internal/registry`,\n")
	b.WriteString("never read from an issuer's published list. A published list is evidence of\n")
	b.WriteString("intent at the time it was written. The account is what is true now.\n\n")
	b.WriteString("This note is generated by the same run that produced the data, so the two\n")
	b.WriteString("cannot disagree.\n\n")

	b.WriteString("## Issuer powers\n\n")
	b.WriteString("| Power | Mints | Share |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| Can take this back from any wallet (permanent delegate) | %d | %s |\n",
		r.WithPermanentDelegate, share(r.WithPermanentDelegate))
	fmt.Fprintf(&b, "| Can freeze this where it sits (freeze authority) | %d | %s |\n",
		r.WithFreezeAuthority, share(r.WithFreezeAuthority))
	fmt.Fprintf(&b, "| Can switch on a check of who may receive this (hook present, disabled) | %d | %s |\n",
		r.WithDisabledHook, share(r.WithDisabledHook))
	fmt.Fprintf(&b, "| Currently checking who may receive (hook active) | %d | %s |\n",
		r.WithActiveHook, share(r.WithActiveHook))
	fmt.Fprintf(&b, "| New accounts start frozen | %d | %s |\n",
		r.FreezingNewAccounts, share(r.FreezingNewAccounts))
	fmt.Fprintf(&b, "| Halted by the issuer right now | %d | %s |\n",
		r.HaltedByIssuer, share(r.HaltedByIssuer))
	fmt.Fprintf(&b, "| Paused on chain right now | %d | %s |\n\n",
		r.PausedOnChain, share(r.PausedOnChain))

	if r.WithActiveHook == 0 && r.WithDisabledHook == r.MintsDecoded && r.MintsDecoded > 0 {
		b.WriteString("The transfer hook row is the one worth sitting with. Not a single mint has an\n")
		b.WriteString("active hook, so a product reporting hooks as a boolean would report none at\n")
		fmt.Fprintf(&b, "all and be wrong about every one of the %d. The hook exists on each of them,\n", r.MintsDecoded)
		b.WriteString("switched off, with a named authority who can switch it on at any moment and\n")
		b.WriteString("without any other change to the mint. Reporting that as absent is not a\n")
		b.WriteString("simplification, it is a different fact.\n\n")
	}

	b.WriteString("## The multiplier field\n\n")
	b.WriteString("| | Mints |\n|---|---|\n")
	fmt.Fprintf(&b, "| Carrying Scaled UI Amount | %d |\n", r.WithScaledUIAmount)
	fmt.Fprintf(&b, "| **Where the field named `multiplier` is stale** | **%d (%s)** |\n",
		r.StaleMultiplier, pct(r.StaleMultiplier))
	fmt.Fprintf(&b, "| Activation scheduled but not yet effective | %d |\n\n", r.PendingActivation)

	b.WriteString("Scaled UI Amount carries `multiplier`, `new_multiplier`, and\n")
	b.WriteString("`new_multiplier_effective_timestamp`. The live value is `new_multiplier` once\n")
	b.WriteString("its timestamp has passed, otherwise `multiplier`. Anything reading the obvious\n")
	b.WriteString("field is one corporate action behind on a third of this market.\n\n")

	var splits []finding
	for _, s := range r.Stale {
		if s.NaiveValue == "1" && s.LiveValue != "1" && !strings.Contains(s.LiveValue, ".") {
			splits = append(splits, s)
		}
	}
	// Largest ratio first, so the sentence below names the most dramatic case
	// rather than whichever symbol sorted first.
	sort.Slice(splits, func(i, j int) bool {
		a, _ := strconv.Atoi(splits[i].LiveValue)
		c, _ := strconv.Atoi(splits[j].LiveValue)
		return a > c
	})

	if len(splits) > 0 {
		b.WriteString("### It is not a rounding error\n\n")
		b.WriteString("| Symbol | The obvious field says | The live value is | Effective since |\n|---|---|---|---|\n")
		for _, s := range splits {
			fmt.Fprintf(&b, "| %s | %s | **%s** | %s |\n", s.Symbol, s.NaiveValue, s.LiveValue, s.EffectiveAt[:10])
		}
		fmt.Fprintf(&b, "\nSplits, where the obvious field never moved from its initial value. Anyone\n"+
			"pricing a position in %s from that field values it at a fraction of what it\nis.\n\n", splits[0].Symbol)
	}

	b.WriteString("The rest are smaller and more insidious: one corporate action behind rather\n")
	b.WriteString("than many, often under a tenth of a percent. That is still a real mispricing\n")
	b.WriteString("on every share, and a system catching only the dramatic cases would pass the\n")
	b.WriteString("splits above and fail silently on the others.\n\n")

	if r.PendingActivation > 0 {
		fmt.Fprintf(&b, "### The opposite error\n\n%d mints had an activation scheduled but not yet\n", r.PendingActivation)
		b.WriteString("effective at capture. Returning `new_multiplier` before its timestamp is\n")
		b.WriteString("exactly as wrong as returning the stale field after it, and only a mint in\n")
		b.WriteString("this state can catch that. One is kept in the fixture set for that reason,\n")
		b.WriteString("resolved against a fixed reference time so the case survives the activation\n")
		b.WriteString("landing.\n\n")
	}

	b.WriteString("## Decoder coverage\n\n| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| Mints decoded | %d of %d |\n", r.MintsDecoded, r.MintsPublished)
	fmt.Fprintf(&b, "| Decode failures | %d |\n", len(r.DecodeFailures))
	fmt.Fprintf(&b, "| Extensions encountered that this build does not recognise | %d |\n\n",
		len(r.UnknownExtensions))

	b.WriteString("The last row is reported because it is the one that will change. When an\n")
	b.WriteString("issuer adopts an extension Seametry has not implemented, it appears here by\n")
	b.WriteString("number rather than being dropped, and it reaches the interface as a sentence\n")
	b.WriteString("saying there is a control we do not yet decode. An unknown that is silently\n")
	b.WriteString("discarded is indistinguishable from an absent one at every layer above, which\n")
	b.WriteString("is how a new issuer power becomes invisible.\n\n")

	b.WriteString("## What this does not establish\n\n")
	b.WriteString("- **Only one issuer.** xStocks mints only. Backpack Securities is not covered,\n")
	b.WriteString("  and its dividend mechanism, a multiplier change or newly minted tokens,\n")
	b.WriteString("  remains an open question that a fixture capture will settle.\n")
	b.WriteString("- **A moment, not a trend.** One slot. The share moves as issuers update\n")
	b.WriteString("  fields, and the large splits will eventually be cleaned up.\n")
	b.WriteString("- **Nothing about intent.** An issuer holding a power is not an issuer misusing\n")
	b.WriteString("  one. Every issuer holding a given power gets the identical sentence here.\n")
	b.WriteString("- **Nothing about depth.** Whether any of these can actually be traded at size\n")
	b.WriteString("  is a separate measurement and a separate ceiling.\n")

	return b.String()
}
