skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hall = "GB1hX1FXQcAUWU23Ji6RtvhTzCKz84ScUsBeD7CqQnjE"

[programs.devnet]
hall = "GB1hX1FXQcAUWU23Ji6RtvhTzCKz84ScUsBeD7CqQnjE"

[provider]
cluster = "localnet"
wallet = '~\.config/solana/id.json'

[scripts]
test = "cargo test"

[hooks]
