package main

import (
	"fmt"
	"strings"
)

// renderNote writes the prose companion to the JSON report. It is generated
// from the same run, because a hand written note about numbers that move is a
// document waiting to disagree with its own data.
func renderNote(r report) string {
	var b strings.Builder

	total, routable, dark := 0, 0, 0
	for _, in := range r.Instruments {
		total++
		if len(in.Points) > 0 && in.Points[0].Availability == "available" {
			routable++
		} else {
			dark++
		}
	}

	fmt.Fprintf(&b, "# Executable depth of %d tokenized equities\n\n", total)
	fmt.Fprintf(&b, "**Captured %s, priced in %s at %d bps slippage tolerance.**\n\n",
		r.CapturedAt.Format("2 January 2006, 15:04 UTC"), r.Quote, r.SlippageBps)
	b.WriteString("Reproduce it with `go run ./tools/depth`. Every raw response is stored\n")
	b.WriteString("unmodified in `fixtures/jupiter/`, addressed by SHA-256, so each figure below\n")
	b.WriteString("can be re-derived from bytes the aggregator actually sent.\n\n")
	b.WriteString("This note is generated by the same run that produced the data.\n\n")

	fmt.Fprintf(&b, "## %d of %d had a route at the smallest size\n\n", routable, total)
	if dark > 0 {
		fmt.Fprintf(&b, "%d had none. That is a finding about the instrument, and the aggregator says\n", dark)
		b.WriteString("why in its own words, recorded verbatim below rather than folded into a\n")
		b.WriteString("generic failure.\n\n")
	}

	b.WriteString("| Instrument | Size (USDC) | Route | Shortfall vs smallest size | Venues |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, in := range r.Instruments {
		for _, p := range in.Points {
			route := p.Availability
			if p.Code != "" {
				route += " (" + p.Code + ")"
			}
			shortfall := "no observation"
			if p.ShortfallBps != nil {
				shortfall = fmt.Sprintf("%d bps", *p.ShortfallBps)
			}
			venues := strings.Join(p.Venues, ", ")
			if venues == "" {
				venues = "none"
			}
			fmt.Fprintf(&b, "| %s | %d | %s | %s | %s |\n", in.Symbol, p.SizeUSDC, route, shortfall, venues)
		}
	}

	b.WriteString("\nShortfall is how much worse the realised rate at that size is than the rate\n")
	b.WriteString("at the smallest size that priced, in basis points rounded up. It is computed\n")
	b.WriteString("in exact arithmetic from the two quotes, not taken from the aggregator's own\n")
	b.WriteString("price impact field. That field is a fraction rather than a percent, which was\n")
	b.WriteString("measured against realised rates rather than assumed, and it is absent at very\n")
	b.WriteString("small sizes, which is not the same as zero.\n\n")

	b.WriteString("## What this does not establish\n\n")
	b.WriteString("- **One aggregator, one moment.** Depth moves continuously and routes change\n")
	b.WriteString("  between calls. These are three samples taken seconds apart.\n")
	b.WriteString("- **Executable is not the same as executed.** A quote is an expiring\n")
	b.WriteString("  proposition. Nothing here was signed or submitted.\n")
	b.WriteString("- **Buying only.** Depth selling into USDC is a separate measurement and\n")
	b.WriteString("  can differ sharply on a thin pool.\n")
	b.WriteString("- **Nothing about intent.** A shallow pool says nothing about an issuer.\n\n")
	fmt.Fprintf(&b, "Spent: %s.\n", r.Spent)
	return b.String()
}
